### ISSUE TITLE
Ponda Boba (V) Should Add 2 To Attrition Destiny Draw, not Total Attrition

### ISSUE THREAD

**Issue by jdipaolo1** [PlayersCommittee/gemp-swccg-public#11]
Expected: Ponda Boba (V) should add 2 to the first attrition destiny draw scheduled, not total attrition

**Comment by stuartshaffer** [comment]
Bug still active.  Just caused an OCS loss.  Would love if this one was fixed.
Replay: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=sshaffer$dhl3gvoh38sgbsy1

**Comment by jdipaolo1** [comment]
We're actually waiting on a ruling for this. It's possible it's already working as the rules team intended.

Background: I believe this card was a holdover from legacy and therefore doesn't have great templating. When there is only one attrition draw, this seems like an obvious bug. But the problem arises when more than one Attrition draw is "scheduled". With the current wording, it's not clear if the +2 is meant to affect the first destiny, or the order in which it was scheduled.

**Comment by jdipaolo1** [comment]
https://forum.starwarsccg.org/viewtopic.php?f=5&t=77635

**Comment by EchoBaseTrooper** [comment]
Ponda Baba (V) received errata (partially because of this bug)
