### ISSUE TITLE
Han's Toolkit unable to cancel Gravity Shadow

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#174]
Expected behavior: Han's Toolkit lights up during the response step of Gravity Shadow (before the destiny is drawn)
Actual behavior: Han's Toolkit does not light up during the response step of Gravity Shadow

Link to game: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jokerking$e0a4tmwe6f1xqr49  (final turn)
Link to rules thread: https://forum.starwarsccg.org/viewtopic.php?f=5&t=76602

**Comment by jdipaolo1** [comment]
NOTE:
Gravity Shadow needs to target the starship first, even if Gravity Shadow ends up ultimately targeting a character aboard the starship.

**Comment by kpbabb** [comment]
Working on this

**Comment by kpbabb** [comment]
This issue can be closed, I just tested it and Toolkit let me cancel gravity shadow with just Han piloting the Falcon and with Han and Rey piloting and Han having the toolkit
