### ISSUE TITLE
Rebel Trooper Reinforcements can deploy to a system as a react.

### ISSUE THREAD

**Issue by seitaer** [PlayersCommittee/gemp-swccg-public#175]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=chrknudsen$4gjc6415g7sszfoy

See subject line. Rebel Trooper Reinforcements should only be able to deploy to a site as a react.

Here's a quick demonstration of them deploying to a system (DS turn 2):

**Comment by jdipaolo1** [comment]
Already fixed.
