### ISSUE TITLE
SATM/BP, Rey w/saber & Code Clearance effect

### ISSUE THREAD

**Issue by seitaer** [PlayersCommittee/gemp-swccg-public#179]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Yodad$igk5ssjcnaouh286

LS Control phase on turn #7. Rey fires light saber using SATM/BP combo and successfully hits Kir Kanos v. Her text allows her to retrieve a force when she hits. After paying the force for retrieval 9required by the Secret Plans shield) DS is able to stack the SATM/BP card on the Code Clearance effect....a bug????

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Hayes$rao0uxgvx9qfrtyo
Turn 5

**relevant ruling**
https://forum.starwarsccg.org/viewtopic.php?f=5&t=72070

**Comment by jdipaolo1** [comment]
I believe this one is already fixed.

**Comment by kpbabb** [comment]
Just tested this on my local copy, made a DS deck with Prepared Defenses, Code Clearance, a location and 57 Kir, made LS deck with a location and a bunch of Rey w/LS and SATM/BP Combo, drained LS to make sure there was force in the lost pile, killed Kir with SATM/BP combo, retrieved force, nothing happened with Code Clearance

**Comment by jdipaolo1** [comment]
@kpbabb thanks for confirming, closing this issue.
