### ISSUE TITLE
Incom Corp vs. Zuckuss in Mist Hunter

### ISSUE THREAD

**Issue by Artd0g** [PlayersCommittee/gemp-swccg-public#184]
I played a game recently where I had set up Incom Corporation and I was in a battle with 3 X-wings vs Zuckuss in Mist Hunter. The game text of that card is supposed to cancel all opponents battle destinies if the opponent doesn’t have at least ability 6. But with Incom Corp and 3 X-wings, I had ability 6. My battle destinies were cancelled and I think this is a bug. Please let me know if you agree. Thanks!

**Comment by jdipaolo1** [comment]
@Artd0g Can you provide a replay link?

**Comment by Artd0g** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Artd0g$nt2fu6sm31szcvde

Does this work?

**Comment by jdipaolo1** [comment]
Yes, thank you. This actually is not a bug.
Zuckuss in Mist Hunter:
**Unless opponent has total ability > 6 piloting here, opponent's total battle destiny here = zero.**

Zuckuss requires "greater than 6 ability", not "at least 6 ability"

**Comment by Artd0g** [comment]
Ah makes sense. Thank you!
