### ISSUE TITLE
Anakin's Podracer - Drawing 3 and Choosing 2 - Only stacks one of the two draws.

### ISSUE THREAD

**Issue by Solidsnack3** [PlayersCommittee/gemp-swccg-public#187]
Anakin's Podracer - Draw 3 and Choose 2 - Does not stack 2 cards on Podrace.

Actual Behavior: Game prompts to draw three and choose 2 in turn beforehand.  Game allows me to draw 3, and even choose 2.  I choose 2 of the 3 draws.  Game gives me the option to stack each destiny.  After yes responses to each, only the first chosen draw is actually stacked.

Expected Behavior: Game prompts to draw three and choose 2 in turn beforehand.  Game allows me to draw 3, and even choose 2.  I choose 2 of the 3 draws.  Game gives me the option to stack each destiny.  After yes responses to each, both draws are stacked.

Dark Turn 3 and Turn 4:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Solidsnck$dzxdh5cac5spa6f5

**Comment by kpbabb** [comment]
I think what is happening is that you pick the first card and your race total becomes higher than theirs, and so it is incorrectly preventing you from adding a second card

**Comment by ideatrack** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$fajh01zdn5rposn2

Yeah, think that's a correct assessment of the bug.
