### ISSUE TITLE
BUG: Lady Proxima shuffles with 2 cards in Reserve

### ISSUE THREAD

**Issue by jagteq** [PlayersCommittee/gemp-swccg-public#197]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jagteq$r7d6ipe55wdg4xd0

On turn 11 in this game, I used Lady Proxima with 2 cards in Reserve.  According to this rules thread (https://forum.starwarsccg.org/viewtopic.php?f=5&t=76669&p=1320191#p1320191), Proxima should not have shuffled Reserve, but according to the game log, it did.  Confirmed that the order changed when I used Nal Hutta as the next action and the Reserve was in a different order on verify.

**Comment by stimpy08** [comment]
Still an open bug, this happened today. https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=stimpy$0a3m65g174gcj0tp

DS Turn 7.
