### ISSUE TITLE
Imperial Class Star Destroyer Non-Unique

### ISSUE THREAD

**Issue by Rambows123** [PlayersCommittee/gemp-swccg-public#198]
I dropped down my destroyer to crush Luke.  However, his destiny to attrition should have destroyed it.  It did not.  My destroyer was immune to attrition less than 4 and he drew a 5.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Rambows$szziwhe9bkm8dl3u

**Comment by EchoBaseTrooper** [comment]
Not a bug. Your opponent didn't draw battle destiny so their attrition was undefined even though there was a destiny to attrition.
