### ISSUE TITLE
Lando with Blaster Pistol does not seem to be programmed as a "Lando" for the sake of Lobot deploying at same site

### ISSUE THREAD

**Issue by D-Burn** [PlayersCommittee/gemp-swccg-public#199]

**Comment by D-Burn** [comment]
Classic Lobot that is, not virtual.

**Comment by D-Burn** [comment]
Here is the game replay link:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=D-Burn$msjy3cn0igb4sa0p

**Comment by EchoBaseTrooper** [comment]
Not a bug. Lobot can only deploy as a react, either to a Cloud City site or where Lando is present.

**Comment by D-Burn** [comment]
That's weird, that seems to go against the syntax of the game text. It reads "Deploys only as a 'react' to a Cloud City site OR to where your Lando is present" (emphasis added). 

I guess technically it could be interpreted either way, but it seems the "react to cloud city site" deployment is the first option and then the "or" he deploys "where your Lando is present." You see what I mean?
Thanks for your time,David
David A. BurnettPhD Student | Religious StudiesJudaism and Christianity in Antiquity
Department of Theology | Marquette UniversityMarquette Hall | 512.659.6857Academia.edu 

    On Friday, November 6, 2020, 01:27:05 AM CST, Adam Fletcher <notifications@github.com> wrote:  
 
 


Not a bug. Lobot can only deploy as a react, either to a Cloud City site or where Lando is present.

**Comment by D-Burn** [comment]
Oh, I see. The "only" refers to the "react," not as in the only two options. 
Sorry,David
David A. BurnettPhD Student | Religious StudiesJudaism and Christianity in Antiquity
Department of Theology | Marquette UniversityMarquette Hall | 512.659.6857Academia.edu 

    On Friday, November 6, 2020, 01:33:35 AM CST, David Burnett <dburnett51@yahoo.com> wrote:  
 
 That's weird, that seems to go against the syntax of the game text. It reads "Deploys only as a 'react' to a Cloud City site OR to where your Lando is present" (emphasis added). 

I guess technically it could be interpreted either way, but it seems the "react to cloud city site" deployment is the first option and then the "or" he deploys "where your Lando is present." You see what I mean?
Thanks for your time,David
David A. BurnettPhD Student | Religious StudiesJudaism and Christianity in Antiquity
Department of Theology | Marquette UniversityMarquette Hall | 512.659.6857Academia.edu 

    On Friday, November 6, 2020, 01:27:05 AM CST, Adam Fletcher <notifications@github.com> wrote:  
 
 


Not a bug. Lobot can only deploy as a react, either to a Cloud City site or where Lando is present.

**Comment by EchoBaseTrooper** [comment]
Yes, I agree the wording on the card is ambiguous. There is a specific ruling to clarify it (page B-11 of the AR):

Lobot (Light Side)
This alien has two deployment
restrictions, and both must be met
simultaneously: (1) he deploys only
as a 'react,' and (2) he deploys only
to a Cloud City site or to where your
Lando is present.

**Comment by D-Burn** [comment]
Ah, I see. I'm sorry, I should have checked the AR first.
But yes, the original syntax can go either way, hence the clarification. 
Appreciate it. 
David A. BurnettPhD Student | Religious StudiesJudaism and Christianity in Antiquity
Department of Theology | Marquette UniversityMarquette Hall | 512.659.6857Academia.edu 

    On Friday, November 6, 2020, 01:37:22 AM CST, Adam Fletcher <notifications@github.com> wrote:  
 
 


Yes, I agree the wording on the card is ambiguous. There is a specific ruling to clarify it (page B-11 of the AR):

Lobot (Light Side)
This alien has two deployment
restrictions, and both must be met
simultaneously: (1) he deploys only
as a 'react,' and (2) he deploys only
to a Cloud City site or to where your
Lando is present.
