### ISSUE TITLE
Hutt influence reducing a drain

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#200]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$cgrzwneij1dnvssq

Hutt Influence shouldn't keep the drain at the site at 2.

Stops the opponent modifying force drains. It's not the opponent modifying it.

**Comment by EchoBaseTrooper** [comment]
Which turn/drain are you talking about?
