### ISSUE TITLE
BUG: Can't redraw Coaxium destinies

### ISSUE THREAD

**Issue by TimeOfYouppi** [PlayersCommittee/gemp-swccg-public#211]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=timeyouppi$b9bpebitl6xwr5we

See light side turn 4. Had Jedi Levitation V in hand and was not given the opportunity to take a character (Luke Skywalker Jedi Master) into hand when drawn as a coaxium destiny. Saw this in an earlier game with Luke Skywalker Rebel Scout V as well.

**Comment by crazyrunnerguy** [comment]
Thanks EBT, didn't see this earlier when I searched for "Kessel."
