### ISSUE TITLE
Wrong icon on Yoda,MOTF (v)

### ISSUE THREAD

**Issue by bkippel** [PlayersCommittee/gemp-swccg-public#216]
He has a rebel icon in gemp instead of a Jedi master icon

**Comment by chrknudsen** [comment]
Updated GEMP ready image below. For some reason, this one is a lot larger than the usual GEMP images, so I've also included a smaller one of the "standard" GEMP size.
![yodamasteroftheforce](https://user-images.githubusercontent.com/74261766/99510840-d1ac8400-2987-11eb-92c3-2f179db5227e.gif)
![yodamasteroftheforce350x490](https://user-images.githubusercontent.com/74261766/99510875-da04bf00-2987-11eb-88da-16e0bfde80ee.gif)
