### ISSUE TITLE
Tantive IV Defense Value Shown as Maneuver Instead of Armor

### ISSUE THREAD

**Issue by BlackbeardBen** [PlayersCommittee/gemp-swccg-public#220]
This is a pretty minor issue I noted when I was looking through the cards on GEMP - the Tantive IV defense value is shown as maneuver instead of armor.  I haven't played it to know if it affects gameplay at all, but at the very least it's labeled wrong on the card.

**Comment by chrknudsen** [comment]
Here's an updated image that should be GEMP ready:

![tantiveiv](https://user-images.githubusercontent.com/74261766/99240341-a47f9a80-27fc-11eb-8599-06f4dd0d8102.gif)

**Comment by EchoBaseTrooper** [comment]
Image updated (only 2 years later...)
