### ISSUE TITLE
LSRS(V) may not be re-drawn by its own gametext when draw for coaxium destiny with Kessel Run (V)

### ISSUE THREAD

**Issue by crazyrunnerguy** [PlayersCommittee/gemp-swccg-public#222]
Title says it all. Have not personally experienced it so no game link, but have seen multiple reports in GEMP and Slack asking whether he should should be able to be re-drawn.

**Comment by EchoBaseTrooper** [comment]
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/211
