### ISSUE TITLE
Better Rez Cards

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#223]
Series 13 cards look amazing. Without changing the cards in any way that the license doesn't allow, could higher rez images of the cards be used? It's esoecially obvious that cards are cut together in cases like Vengance V.

there are a lot of places where higher rez versions of cards exist:
https://forum.starwarsccg.org/viewtopic.php?f=188&t=65510
https://scomp.starwarsccg.org/

and if the errata/text needs updating, maybe just replace the text part of the card.

Would be great to see all the cards looking the way the new ones do.

**Comment by DevoKun** [comment]
@ideatrack , higher resolution cards are put in to service when available. You can find out repository of images in the [holotable repo](https://github.com/swccgpc/holotable). There is a project underway to update the quality of the older cards, but it is slow going. If you or somebody you know has some cycles to donate to the graphics team it could help move us forward.
