### ISSUE TITLE
Dejarik cards can be targeted as interrupts and effects when deployed

### ISSUE THREAD

**Issue by DSx61x4** [PlayersCommittee/gemp-swccg-public#230]
Per the rules:
"Dejariks and holograms at a holosite are not considered to be Interrupts and Effects (except for cards that specifically refer to them at a holosite), they are simply dejariks and holograms (e.g., Alter may not cancel Molator at the holosite). However, any card which specifically names a dejarik or hologram card may still affect that card (e.g., Grimtaash specifically cancels Molator)."

Currently Sense and Alter are able to target and cancel Dejarik cards deployed to holotable/hologameboard.

**Comment by DSx61x4** [comment]
I think I saw a changelog entry where Sense and Alter could no longer target cards deployed to a holosite.  I have not tested it, but assuming the changelog fix is correct, this can be closed.

**Comment by DSx61x4** [comment]
Scratch out my above comment.  It was claimed to be fixed:
Changelog: "6/10/2021 Bug Fix: Dejariks & holograms should not be targetable by sense/alter while they are at a holosite"
However the problem still exists.  It is possible Sense and Alter won't target cards deployed to the holosites, but Sense, Alter, and Grabbers still target the cards as they are being deployed as if they are being played rather than deployed.

**Comment by scottrick** [comment]
I fixed this here, but it still needs to be merged / approved.  This is my first contribution to gemp so I expect EBT will want to take a good look before merging :D

https://github.com/PlayersCommittee/gemp-swccg-public/pull/537

**Comment by EchoBaseTrooper** [comment]
Thanks @scottrick for fixing this!

**Comment by scottrick** [comment]
Thanks for merging!!
