### ISSUE TITLE
>5 Filter in Merchant

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#232]
Just discovered that the =>5 filter doesn't seem to work in the merchant.

It pulled back no cards at all, but when I filtered on =>4 and it returned some cards where I had 6 or 7 copies and should have been shown in the above filter as well.

**Comment by EchoBaseTrooper** [comment]
Seems to be working fine to me. If you have screenshots or something you can submit another bug report.
