### ISSUE TITLE
Bug - Surprise and Smoke Screen

### ISSUE THREAD

**Issue by cringwell** [PlayersCommittee/gemp-swccg-public#233]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=advocate$spsofckepl3tyacw

Dark Turn 5.  He played smoke screen targeting Yoda, I played Surprise to retarget it to General Leia, but it still gave him 7 in battle destiny.  

https://imgur.com/ldrNSKO

**Comment by cringwell** [comment]
Don't know how to make it a 'bug'

**Comment by cringwell** [comment]
So I used the lightside mirror in a game, retargeting Short Range fighters to use the maneuver of another ship in the same battle.  That actually worked and used the lower maneuver.  So not sure if that helps.

**Comment by EchoBaseTrooper** [comment]
Yes, when I fixed Surprise + Smoke Screen I made sure all of the similar cards worked correctly

**Comment by cringwell** [comment]
Oh, didn't realize it was fixed. Excellent!
