### ISSUE TITLE
A New Hope Wedge - No Modifiers on Red Squadron 1

### ISSUE THREAD

**Issue by Solidsnack3** [PlayersCommittee/gemp-swccg-public#234]
A New Hope Wedge does not appear to add his modifiers on his character card to Red Squadron 1.

Actual: A New Hope Wedge is piloting Red Squadron 1, he does not add to maneuver and does not draw if unable to otherwise.

Expected: A New Hope Wedge adds to maneuver and draws one battle destiny if unable to otherwise.

Based on the current coding, the old New Hope Wedge just refers to the specific red 2 card, and not the red 2 personna.

**Comment by Solidsnack3** [comment]
Pull request made to fix this issue.

**Comment by EchoBaseTrooper** [comment]
I mentioned this on the pull request, but are you sure this is currently a bug? It seemed to work correctly when I tested it.

**Comment by Solidsnack3** [comment]
Hello Adam,

Someone else reported it and I thought I knew what the issue was, but
re-reading the code I see that it does define the piloting condition in the
A New Hope Wedge.  I should have tested this further.

Apologies for the request and taking up your time.
-James
