### ISSUE TITLE
Tobias Beckett and Kessel Run

### ISSUE THREAD

**Issue by CoffeePassport** [PlayersCommittee/gemp-swccg-public#236]
Apologies for lack of a game to show but I have seen it multiple times: when Tobias Beckett is drawn as a destiny for Kessel Run, it stacks him as a 0, not a 3. (The game log says "3," but he is counted as a 0 in the total and causes the Run to keep drawing cards/fail even when it would hit > 12 with him.)

**Comment by EchoBaseTrooper** [comment]
I believe this is working correctly. When he is stacked he loses the destiny +3 modifier. If you think it should be working differently could you ask a rules question about this?
