### ISSUE TITLE
Bug regarding I Think I Can Handle Myself

### ISSUE THREAD

**Issue by bibfortuna25** [PlayersCommittee/gemp-swccg-public#238]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bibfortuna$y8y9or18nu62ihmj

Dark side turn 3. I was unable to play I Think I Can Handle Myself to cancel the weapon destiny from the AAT Laser Cannon.

**Comment by EchoBaseTrooper** [comment]
Not a bug. Maul says "Opponent may not cancel your destiny draws."
