### ISSUE TITLE
Bug: Saber 1 not Making X 3 when 1 force used

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#239]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$0bi4hecrw8x3qldy

I'm sure this has worked before, but maybe only with a matching pilot. if so, that's a bug at it's saber 1's text, regardless of pilot, that makes x=3 for 1 force.

**Comment by EchoBaseTrooper** [comment]
To use Saber 1's text you should first use 0 Force with the weapon, then it will let you click on Saber 1 to use its text to use 1 Force and make X=3.
