### ISSUE TITLE
Ships with no pilot are able to embark/disembark

### ISSUE THREAD

**Issue by paulklein22** [PlayersCommittee/gemp-swccg-public#253]
I played Eject, Eject! on a Black Squadron TIE taking out its permanent pilot. That same turn, with no pilot on the ship, my opponent was still able to embark/disembark the TIE on his capital ship. The rules state that ships require a pilot to embark/disembark.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by paulklein22** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Elrood$lw0h4xqpncj1tsme

Eject, Eject! is played on Turn 1. The pilotless TIE embarks on a Dreadnuaght on Turn 4.

**Comment by EchoBaseTrooper** [comment]
AR 9-16 says "An unpiloted starship at the same system
as a capital starship may embark on board that starship
if possible, or may have cards move between it and a
docked starship (these are specific exceptions to the
"may not move" rule)."

So it doesn't look like this is a bug.
