### ISSUE TITLE
Rescue In The Clouds not cancelling destiny draw for Control & Set For Stun

### ISSUE THREAD

**Issue by CoffeePassport** [PlayersCommittee/gemp-swccg-public#255]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CoffeePass$yy587iwkkgm9abi1

Turn 4, Light Side's move phase: Control & Set For Sun is played targeting Bail Organa. Dark Side draws destiny and Rescue In The Clouds does not light up to cancel it -- reverted twice to check, never lit up. Rescue is grabbed, but there is sufficient force to pay for it and doesn't look like any other interaction on the table that would be preventing it.

**Comment by EchoBaseTrooper** [comment]
Maul didn't let you cancel the destiny draw
