### ISSUE TITLE
Bug: Deploying with and without Presence from spies

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#264]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$e1fhxddsdlxv8iuo

Early on my opponent deploys to ObiWan's Hut without presence via U3PO being there. We discussed it at the time. and I thought this was a bug. My opponent said that you can deploy to a site with a spy droid.

Later in the same game I could not deploy to the War room, despite having R2D2 there (a droid spy). One of these has to be a bug.

**Comment by chrknudsen** [comment]
Neither is a bug. Per the rules, an _**Undercover**_ spy allows you to deploy there without presence or Force icons.
