### ISSUE TITLE
Bane Malar - Res Luk Ra'auf

### ISSUE THREAD

**Issue by ckroutil** [PlayersCommittee/gemp-swccg-public#265]
Res Luk Ra'auf does not work with Bane Malar.

I used RLR correctly- Bane was defending a battle alone and is a bounty hunter.  I have used RLR successfully with many other characters and it has not worked only with Bane.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by ckroutil** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ckroutil$dh6tam8dllc3vhes

Light side,  turn #6 ( battle). The interrupt does not highlight.

**Comment by EchoBaseTrooper** [comment]
There wasn't enough force to play it since it had been grabbed

**Comment by ckroutil** [comment]
Doh!
