### ISSUE TITLE
Redemption Bacta Tank 'patient' deploy cost

### ISSUE THREAD

**Issue by Bespin8** [PlayersCommittee/gemp-swccg-public#266]
Not sure if Redemption is coded to recognize a 'patient' or not, but when I take a char off of bacta tank and deploy on Redemption on LS deploy turn 5, it was not free to do the deploy. 

Here's the game link:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=winstonp$utqoagolkek26fjo

**Comment by EchoBaseTrooper** [comment]
They deploy directly from the Bacta Tank to Redemption. The way to do it in GEMP is to click on the ship during your deploy phase and it will let you deploy them straight from the Bacta Tank.
