### ISSUE TITLE
Homing Beacon on GEMP

### ISSUE THREAD

**Issue by DTartagOne** [PlayersCommittee/gemp-swccg-public#270]
![homingbeacon](https://user-images.githubusercontent.com/77410119/104497802-c04eb500-558f-11eb-9fb4-c77a31e59f06.gif)

The bug is the movement text.  During a battle, Homing Beacon is highlighted so that it can be used to react a starship.  However upon clicking the card and the desired ship, nothing happens.  It does allow for multiple clicks.

**Comment by EchoBaseTrooper** [comment]
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/64
