### ISSUE TITLE
Opponent transited to Executor DB for free

### ISSUE THREAD

**Issue by ckroutil** [PlayersCommittee/gemp-swccg-public#279]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ckroutil$m145lj4hws72l82x

Light side turn 5, Leia transits from Yavin DB to Executor's for free. 

I'm not sure if this transit is supposed to be free because of the Y4DB gametext or if it's supposed to be +9.  Is it free meaning "free" or is it free meaning "free +9"?

**Comment by EchoBaseTrooper** [comment]
Free is unmodifiable, so the +9 doesn't do anything in this case.
