### ISSUE TITLE
[Bug] Unable to fire Leia's Sporting Blaster while deployed on General Solo

### ISSUE THREAD

**Issue by DingusMyDingus** [PlayersCommittee/gemp-swccg-public#288]
Situation:  During my control phase I attempted to fire Han's Blaster Pistol (V) at Jodo.  Opponent played Any methods Necessary, sending the blaster to my used.

During my deploy phase I deployed Leia's Sporting Blaster on Han, and then initiated battle.  During battle it would not allow me to fire.  This may be a bug related to Any Methods Necessary rather than Leia's Sporting Blaster.

**Comment by EchoBaseTrooper** [comment]
The Advanced Rulebook says "Unless specified otherwise, each character, vehicle or starfighter may use (as in using its game text) only one weapon per turn". Since Han used Han's Blaster Pistol (V) earlier in the turn he wouldn't have been able to use a different weapon on the same turn.
