### ISSUE TITLE
[Bug] Stay Sharp! not recognizing gunners to add 2 to total weapon destiny.

### ISSUE THREAD

**Issue by DingusMyDingus** [PlayersCommittee/gemp-swccg-public#289]
I had The Falcon with: Concussion Missiles, Kin Kian and Karie Neth aboard.  Both Kin Kian and Karie Neth are gunners (lore).

During my control phase I play Stay Sharp! to target my opponent's starship present (it was Devastator).  I draw a 5 for destiny and the total destiny is immediately set to 8.  (Karie adds 1 and Kin adds 2).  There was no option to "If Han or any gunner is aboard that starship, may add 2 to the total weapon destiny" from Stay Sharp!'s gametext.  The total destiny should have been 10.

This is a different issue to one I have seen with Jodo Kast's gametext which says "may add 2" but is currently being applied automatically to the first time he shoots an appropriate weapon on a given turn.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by DingusMyDingus** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Dingus$cech43dac9zjwrc4

Happens on turn ~3 I think.

**Comment by EchoBaseTrooper** [comment]
It isn't obvious how this works in GEMP, but to apply the optional +2 an image of the card pops up when you draw the destiny. You click on that to add 2.
![image](https://user-images.githubusercontent.com/45436940/105778358-81bee000-5f29-11eb-9931-58cf484c05ed.png)

**Comment by DingusMyDingus** [comment]
Thanks, I replayed it twice looking for something akin to this happening and missed it all 3 times.  GG.
