### ISSUE TITLE
Omni Box might have broken the game with Sy on the table

### ISSUE THREAD

**Issue by cringwell** [PlayersCommittee/gemp-swccg-public#296]
https://gemp.starwarsccg.org/gemp-swccg/game.html?gameId=252

game is frozen.  

I was about to shuffle his reserve deck with Omni Box combo, it highlighted the reserve decks and then the red text came on asking to refresh and now the game is stuck

**Comment by EchoBaseTrooper** [comment]
This was fixed but I never closed this report
