### ISSUE TITLE
Missing Cards in New UI Deckbuilder

### ISSUE THREAD

**Issue by GreedoJuice** [PlayersCommittee/gemp-swccg-public#298]
Hello,

I was in Deckbuilder on the new UI today and could not locate(missing) the following cards: Xizor's Palace: Sewer and Xizor's Palace: Uplink Station. 

The cards are available to me in the old UI though.

Thanks for all the hard work!!
Matthew Ulmes
GEMP: Chedda
Forum: GreedoJuice

**Comment by SWCCGArenaProject** [comment]
Thank you for the report!  I've just put up a PR for the 1.5.9 gui which will fix this problem.  As soon as that is deployed we can confirm and close this ticket.
