### ISSUE TITLE
BB8 couldn't be captured by Nute Gunray V

### ISSUE THREAD

**Issue by kissmywookiee** [PlayersCommittee/gemp-swccg-public#299]
BB8 was forfeited at same site as Nute Gunray V. I had the option to capture, but BB8 then went to used pile. Reverted to confirm a prompt wasn't missed

Dark Side turn 5 battle phase
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=wcullen$0crpz7jpestfwrav

**Comment by EchoBaseTrooper** [comment]
It looks like he is missing a warrior icon
