### ISSUE TITLE
Han’s Toolkit & Flawless Marksmanship 

### ISSUE THREAD

**Issue by Silverglen** [PlayersCommittee/gemp-swccg-public#314]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Silverglen$gi57tactw7vvk5y7

Move phase turn 4.

As ruled by Gergall HT should have the opportunity to cancel FM as it implies the Falcon as its target. I had the 1 force available to do so. Gemp did not offer me the option.

thanks

**Comment by jokerking16** [comment]
May be a similar issue to this previously reported bug.  

https://github.com/PlayersCommittee/gemp-swccg-public/issues/174
