### ISSUE TITLE
Jedi Lightsaber not adding to force drain

### ISSUE THREAD

**Issue by r-chou-d2** [PlayersCommittee/gemp-swccg-public#316]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=r_chou_d2$pr9bkksfyqjuednl

COTVG (DS) vs Tatooine CPv (LS). Apparent bug occurs turn 4 and after.

"Luke Skywalker, the last Jedi" is armed with the non-unique "jedi lightsaber". Drain initiates, I'm able to click on the lightsaber to add, but that +1 isn't in the total. A turn later Luke moves to another site to drain and same issue happens. 

There does not appear to be any objective, effects or other cards on table to would impact this addition. 

Help or explanation is appreciated. Thanks.

**Comment by jediosu** [comment]
The JCC cancels non-unique lightsaber drain bonuses
