### ISSUE TITLE
Epic duel not working

### ISSUE THREAD

**Issue by adorold** [PlayersCommittee/gemp-swccg-public#324]
Playing a hdadtj deck. Used Vader’s obsession but couldn’t use epic duel, so objective was placed out of play. Is this a bug or did I do something wrong?

**Comment by EchoBaseTrooper** [comment]
Do you have a replay? You have to use it a specific way but I don't remember right now exactly what that is.

**Comment by adorold** [comment]
I don’t, we just started using the system and not sure how to do that

**Comment by EchoBaseTrooper** [comment]
Welcome to GEMP! Are you using the traditional black and white UI or https://gemp.starwarsccg.org/gemp-swccg/newgui.html?

Traditional: At the top of your screen go to Game History. There is a "Replay game" link on the right. Copy the link address for that game and paste it here (it will look like this: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=echobstrpr$iirmckstf5iuk9f2)
Epic Duel: Go to History and copy the Replay ID for that game and paste it here (it will look like this: echobstrpr$iirmckstf5iuk9f2)

Let me know if you have any issues getting the replay.
