### ISSUE TITLE
Evacuation control let me deploy a site from it as if from hand

### ISSUE THREAD

**Issue by arebelspy** [PlayersCommittee/gemp-swccg-public#329]
site lit up and let me deploy it as if from hand

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=arebelspy$g0huyhh5uu27612r

Light side turn 5 deploy phase.

I know evac is getting blanked, but bug potentially still relevant if/when code reused for new version.

**Comment by Ericobasso** [comment]
I had a similar issue last night with Imperial Justice v: it let me deploy a system as if from hand. I tested it and reverted, as I didn't want to deploy the system and it was an OCS match.
