### ISSUE TITLE
Vaporator able to deploy on Sandspeeder at Farm

### ISSUE THREAD

**Issue by BlackbeardBen** [PlayersCommittee/gemp-swccg-public#334]
I played a game today where when I had a Sandspeeder at a Farm, and chose to deploy a Vaporator there from the reserve deck via the site's game text.  I was able to deploy it on to the Sandspeeder itself, not just the site!  It even moved with the Sandspeeder and still provided its modifiers when I moved it.

Replay link (see LS turn 2):
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BenKenobi$slaufwr9g8hdwm0s

**Comment by EchoBaseTrooper** [comment]
Should be fixed now

**Comment by DSx61x4** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DSx61x4$sncjjn03zdyn3grq
Turn 4.
