### ISSUE TITLE
Beggar Mischategorized and not Shown with proper filters

### ISSUE THREAD

**Issue by billbisco** [PlayersCommittee/gemp-swccg-public#337]
Beggar is a Premier Lightside Card but is not properly showing up in filters

![Beggar Not Shown](https://user-images.githubusercontent.com/18236252/112502962-e8f9e480-8d60-11eb-9ad2-b79bfd65c7b7.PNG)

**Comment by EchoBaseTrooper** [comment]
Filtering by format removes Beggar. Beggar is banned in every format because it crashes the server in certain situations.
See #224
