### ISSUE TITLE
[bug] (?) Opponent activates at Endor system while Strike Planning on the table

### ISSUE THREAD

**Issue by Ericobasso** [PlayersCommittee/gemp-swccg-public#338]
I just played an OCS match where opponent got 2 extra activation while I had Strike Planning on table. Opponent was not playing EOPS. See the link below, LS turn 4.

Maybe I missed something, but it seemed like a bug.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Ericobasso$3itxdmg85aj58d3e

**Comment by EchoBaseTrooper** [comment]
Endor was never deployed in this game. Naboo was deployed on turn 4.
