### ISSUE TITLE
Kal'Falnl C'ndros able to board Falcon using shipdock

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#340]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jokerking$b1yfga23h3hu0lvg
LS final turn.

Expected behavior: Kal'Falnl C'ndros is unable to move over to a starfighter that is shipdocked.
Actual behavior: Kal'Falnl C'ndros is able to move onto the starfighter.

**Comment by EchoBaseTrooper** [comment]
Duplicate of #221
