### ISSUE TITLE
Tarkin Doctrine giving force loss at Death Star.

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#341]
DS Turn 4 (or 5): While Death Star is a battleground, Tarkin Doctrine was able to give a 1 force loss to LS. The appendix B entry in AR 3.27 states that Death Star should be excluded if it becomes a battleground.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$eeka3e10ue5x2u6e

**Comment by EchoBaseTrooper** [comment]
Fixed
