### ISSUE TITLE
Lando Casino Retrieval - Present when Aboard AT-AT - bug

### ISSUE THREAD

**Issue by Solidsnack3** [PlayersCommittee/gemp-swccg-public#344]
Lando is at the Cloud City Casino Site and Aboard an AT-AT.  Lando is not present at Cloud City Casino since he is aboard the At-At

Actual behavior:
Lando plays sabacc, wins (lucky me), nothing wrong here.
Cloud City Casino allows me to retrieve 3, potentially believing Lando is present.

Expected Behavior:
Lando plays sabacc, wins (hopefully!), but cloud city casino's text should not kick in unless I have disembarked from the At-At

Replay light side turn 5 and Dark Side turn 6.  Not sure how I didn't catch it since this is something I've given a lot of thought to (especially to prevent personna replacement for Lando).
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Solidsnck$0yew0c4b82v53db3

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
