### ISSUE TITLE
Bug: Lady Proxima not allowing alien to be taken into hand with less than 3 cards revealed

### ISSUE THREAD

**Issue by deadbody55418** [PlayersCommittee/gemp-swccg-public#351]
Used lady proxima with 1 card in reserve, it was Cad Bane (alien).  Was not able to take into hand.  Reverted to see if I just misclicked.  Cad was not highlighted and was not able to be selected.

**Comment by EchoBaseTrooper** [comment]
Not a bug. https://forum.starwarsccg.org/viewtopic.php?p=1320190#p1320190
