### ISSUE TITLE
I Have a Bad Feeling About This -  Does not check for Han's Location

### ISSUE THREAD

**Issue by billbisco** [PlayersCommittee/gemp-swccg-public#352]
Used "I Have a Bad Feeling About This" when a battle was initiated.  There was no option to indicate that Han was present and that battle damage should be tripled instead.

See replay:  Battle damage should be 48  (18*3) instead of 36 (18*2) 

Dark side total power: 21
Light side total power: 39
Light side wins battle
billbiscos has 4 attrition remaining, but all cards are immune
DSx61x4 has 23 attrition and 36 battle damage remaining to satisfy
DSx61x4 lost due to: Conceded
billbiscos is the winner due to: Opponent conceded

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=billbiscos$dgl1864fr489mnao
![Bug in GEMP - Damage not Tripled](https://user-images.githubusercontent.com/18236252/115974086-3ddb7700-a528-11eb-9bf2-f942494480ba.PNG)
[GEMP Bug Battle Damage not Tripled Game Log.docx](https://github.com/PlayersCommittee/gemp-swccg-public/files/6370830/GEMP.Bug.Battle.Damage.not.Tripled.Game.Log.docx)

**Comment by EchoBaseTrooper** [comment]
I've Got A Bad Feeling About This says "(if Han is present at the battle location, triple opponent's battle damage)." Han was on a starship and was not present at the location.
