### ISSUE TITLE
Unable to deploy Qui gon with lightsaber

### ISSUE THREAD

**Issue by JediJer** [PlayersCommittee/gemp-swccg-public#358]
Private game testing a deck and on turn 4 Light was unable to select Quigon with lightsaber as a valid deploy action.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jedijer$wtmr8ft7h0om7nsc

**Comment by EchoBaseTrooper** [comment]
It looks like Qui-Gon's Lightsaber was already on the table (on General Kenobi)
