### ISSUE TITLE
Yoda, Master Of The Force (V) Card Image Missing from Epic Duel

### ISSUE THREAD

**Issue by DevoKun** [PlayersCommittee/gemp-swccg-public#360]
The card image for `Yoda, Master Of The Force (V)` seems to be missing from **Epic Duel**. 

![](https://res.starwarsccg.org/cards/Virtual13-Light/large/yodamasteroftheforce.gif)

This seems to affect the play in **Epic Duel** making the card not visible to either side _(i.e. it appears to be played face down)_.

![image](https://user-images.githubusercontent.com/20324983/118032492-5a9beb00-b32d-11eb-8a98-b90434aec1d6.png)

The card does exist in the normal **Gemp Deck Builder**.

![](https://user-images.githubusercontent.com/935976/118038971-c8501300-b33d-11eb-8fa5-7e2205157d79.png)

GEMP Replay ID: `DarthHugo$oazbyoc1vpa9nw9i`

**Comment by DevoKun** [comment]
Transferred issue from [`scomp`](https://github.com/swccgpc/swccg-scomp/issues/6)

**Comment by EchoBaseTrooper** [comment]
I'm not sure when this was fixed, but it is there now.
