### ISSUE TITLE
Mant Sav Wouldn't allow me to forfeit from hand

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#361]
ideatrack$lsjanye14ej1sk5y

I can lay mant sav at the very end there.
Doesn't affect the game, but I lost and had a character in hand, so should have been able to I think?

**Comment by EchoBaseTrooper** [comment]
Which battle are you talking about? I watched through the replay and Savrip lit up every time it was supposed to. You might have clicked pass accidentally on using Savrip.
