### ISSUE TITLE
Shadow Collective: cannot add destiny to power with Xizor

### ISSUE THREAD

**Issue by FlorisDeVijfde** [PlayersCommittee/gemp-swccg-public#365]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**

The destiny to power does not work when you choose to recirculate first during opponent's turn.  I had Xizor at 3rd marker, LS initiated a battle, Xizor shot a guy, hit, the objective flipped and lit up. I could recirculate, which I did, but during the weapons phase I was not able to add a destiny to power. Normally the objective needs to light up for that action as well, but it was no longer possible after the recirculate. It seemed later that when I didn't choose to recirculate with Hondo, I was able to add the power destiny however. So the recirculate seems to frustrate it.

## **To Reproduce**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=FlorisV$gchmxvvmwryrfhp1
The Shadow Collective objective after Xizor hits a target on turn #4 of LS player MartyMcFly. It's not available as an option for adding the power destiny.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=FlorisV$gchmxvvmwryrfhp1

## **Expected behavior**
Flipped objective should light up to enable the optional Power destiny after recirculating during opponent's turn.

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX, Mojave 10.14.6
 - Browser [e.g. chrome, safari] Chrome Version 90.0.4430.212 (Officiële build) (x86_64)

**Comment by EchoBaseTrooper** [comment]
General Airen Cracken says "Opponent may not add destiny draws to power or attrition here."

**Comment by FlorisDeVijfde** [comment]
Thanks, very sharp! Never had a clue!
