### ISSUE TITLE
Bothawui Not Stopping Hutt Smooch

### ISSUE THREAD

**Issue by hustlertwo** [PlayersCommittee/gemp-swccg-public#367]
Hi!  I played a Scavenger game against Yard and occupying Bothawui did not prevent him from targeting an Undercover spy with Hutt Smooch. Going by the text on the card, occupying the system protects all Jndercover characters from Hutt Smooch. Let me know if you need more info. Thanks!

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=hustlertwo$oq4f5o0pqvtneyd3

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
