### ISSUE TITLE
Hidden Base is limited to Force drain 1 after flipping and then getting objective placed OOP vs Hunt Down (v)

### ISSUE THREAD

**Issue by Echotun** [PlayersCommittee/gemp-swccg-public#373]
Hi
I was just playing my Hidden Base against my friends Hunt Down (v).  

I flipped my objective on my turn 4, and he probed my hidden base at Nar Shaddaa the next turn with Emperor's Shuttle and placed it out of play. From then on I was still force draining for 2 at Kessel (his objective removed the +1), but he was limited to only 1 force loss for the remainder of the game.

Replay link:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Echotun$uoh094luvfrsmfp5

I flip on my turn 4
He probes on his turn 5.

Regards
Thomas Caspersen

**Comment by jdipaolo1** [comment]
Should be addressed in latest release.
