### ISSUE TITLE
Allow AI Foilization

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#379]
Currently, GEMP AIs are awarded as prizes.  When a user has accumulated 4 copies of an AI, the Trade 4 for foil option is missing.

If this is intentionally blocked, this ticket can be closed.
If it is a matter of programming the functionality into hte Merchant, I think foil-lovers like myself would be appreciative.

**Comment by EchoBaseTrooper** [comment]
It is intentionally blocked. It's more than just the merchant that would need to change and I think it's too much work for how much it would be used.
