### ISSUE TITLE
Mismatched Format Names (Open no v-cards / Decipher cards only)

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#384]
## **Describe the bug**
Not so much a bug as an annoyance.  These two formats are identical except for the different names.  Decipher Cards Only appears in the Lobby and Format Info sections, but Open (No V-Cards) appears in the Deckbuilder Format list.

**Comment by EchoBaseTrooper** [comment]
Fixed in the latest release
