### ISSUE TITLE
Chirrut unable to target Baze in lost pile to retrieve, triggered lost pile verify instead

### ISSUE THREAD

**Issue by sgcstearns** [PlayersCommittee/gemp-swccg-public#385]
## **Describe the bug**
Dark side battle phase turn 9
Chirrut lost during battle, Baze in lost pile.  Triggered a verify of lost pile as there was "no card to retrieve".  

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=sgcstearns$9858e2pk0yop7mr4

## **Expected behavior**
Should have been able to target to retrieve Baze.  I satisfied coward and had force to pay for secret plans.  I would also have expected to be able to try and retrieve and have it fail rather than verify the lost pile.  

### **Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 91

## **Additional context**
Dannik Jerriko was previously at the site and lost (before this turn), maybe his text about removing from lost pile was still applying?

**Comment by seitaer** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Ryder$pjtu39un5jwxi26z

Just adding another similar issue to this where Baze is not being treated as a spy by the objective.

**Comment by sgcstearns** [comment]
Were y'all able to reproduce and fix this bug?  Or did me & opponent miss something on table that prevented this?  

While the linked issue is related to Baze, I see no reason why the cause for Baze not being a spy in no idea would have the same cause as the Chirrut & Baze interaction (which occurs regardless of objective).

Thanks!
