### ISSUE TITLE
Homing Beacon Does Not Cancel Landing Claw

### ISSUE THREAD

**Issue by ckroutil** [PlayersCommittee/gemp-swccg-public#390]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ckroutil$uh5bc3iaasb37m50

Turn #7 for Dark Side. During Move Phase.

There's no option to click either the Homing Beacon or the Landing Claw to cancel it. I tried this specifically during DS move phase. 

Also, in another game, I was not able to use the Homing Beacon to react to a battle. I reported this several months ago.

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
