### ISSUE TITLE
Actions appear in the Dropdown as 'Action 1, Action 2' in the new UI

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#391]
## **Describe the bug**
Instead of giving an overview of what you can do the actions come up as 'action 1 action 2' instead of embark, move etc

## **To Reproduce**
Go to any action and click on a card that can do multiple actions

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$msztyxviulbhgiy1

## **Expected behavior**
Shoudl display available actions

## **Screenshots**
I did not take any at the time, but seems to be easily reporoduced by all

## Client Platform
Mac

### **Smartphone (please complete the following information):**
n/a

## **Additional context**
This has also been reported by another user on the general forum so I exoect it is widespread.

**Comment by EchoBaseTrooper** [comment]
Fixed
https://forum.starwarsccg.org/viewtopic.php?p=1348077#p1348077
