### ISSUE TITLE
dannik jerriko (v)

### ISSUE THREAD

**Issue by pwbicker** [PlayersCommittee/gemp-swccg-public#392]
Inconsistency with card text "Opponent's characters just lost from here may not be removed from lost pile" and implementation as shown in the chat which says "•Dannik Jerriko (V) prevents characters lost from here being removed from lost pile. until end of the turn"

**Comment by jokerking16** [comment]
Current text:

•Dannik Jerriko (V) required response is initiated
•Dannik Jerriko (V) prevents characters lost from here being removed from lost pile. until end of the turn

A couple of text cleanup recommendations:

1) Use the character name as it is lost.  (ie.  **•Daughter Of Skywalker may not be removed** from lost pile. until end of the turn)
2) Capitalize "Lost Pile" and remove period before "until end of turn".
3) Remove "the" before "turn"

Finalized suggestion:

•Dannik Jerriko (V) required response is initiated
•_Character Name_ may not be removed from Lost Pile until end of turn.

**Comment by jediosu** [comment]
This appears to have already been fixed 7/23/2021 per gemp changelog
