### ISSUE TITLE
Palpatine, Emperor Returned does not return to hand when lost.

### ISSUE THREAD

**Issue by bear1770** [PlayersCommittee/gemp-swccg-public#394]
## **Describe the bug**
Palpatine, Emperor Returned says 'Once per game, if about to be lost, may take him in to hand.'.  In a game I was playing, on turn #5, I lost him to attrition and the prompt came up to use that game text.  He did go into my hand for a split second, but then immediately to the lost pile.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bear42$m9ofgb9xpj0m81i3

## **Expected behavior**
He should stay in my hand.

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101 

## **Additional context**
I couldn't see any other game effect that would have caused that kind of behavior.

**Comment by EchoBaseTrooper** [comment]
This was fixed shortly after this bug was reported but the ticket was never closed.
