### ISSUE TITLE
No Destiny added by Battle droids

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#396]
## **Describe the bug**
Destiny wasn't added in battle by the battle droids

## **To Reproduce**
end fo the game before the cancel, my opponent doesn't draw destiny

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$zs94u7vosi2bsory

## **Expected behavior**
should be adding destiny

## **Screenshots**
see GEMP replay

### **Desktop (please complete the following information):**
Mac Big Sur

## **Additional context**
Another bug with podrace happened just before, might be related, I'll report seperately

**Comment by jdipaolo1** [comment]
both of the gemp replays didnt work, could you try uploading them again?

**Comment by ideatrack** [comment]
I'd pasted the URL at the time - edited afterwards with replay link. Looks to be working now.

**Comment by EchoBaseTrooper** [comment]
The droids seem to work fine. This was most likely caused by the podracing bug.
