### ISSUE TITLE
Adding an 'All Virtual' filter

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#400]
## **Describe the solution you'd like**
You can already select a filter of Virtual ), 1 etc - but would be good to be able to select all Vurtual Cards as one filter

## **Describe alternatives you've considered**
Works fine as-is, just an enhancement

**Comment by EchoBaseTrooper** [comment]
The rarity filter has a Virtual option. Does that work for what you want?

**Comment by ideatrack** [comment]
Yes, perfect. Makes sense actually! I hadn't seen it was there. Thanks.
