### ISSUE TITLE
Can't deploy Luke in Space from Lost Pile using BHBM

### ISSUE THREAD

**Issue by ckroutil** [PlayersCommittee/gemp-swccg-public#404]
Turn #5 LS, deploy phase.

Luke was in lost pile, Red 5 was in hand. Attempted to deploy Luke to Coruscant in Red 5 but it wouldn't let me.  I figured I could do this due to the wording of BHBM.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ckroutil$s5t8d4jxm2tnpie7

**Comment by bibfortuna25** [comment]
BHBM’s deployment action is a top-level action. When you deploy an empty starfighter to a system, you have to supply a pilot for it from your hand. There is no opportunity to deploy Luke from your Lost Pile simultaneously with the ship because that is a separate action.
