### ISSUE TITLE
Add a Filter for Non-Virtual

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#405]
## **Is your feature request related to a problem? Please describe.**
No issue

## **Describe the solution you'd like**
We have a 'Virtual' Under the Rarity filter - can we have a Non-virtual. With Many cards having the same image and the same title, I really don't want to accidentally sell my Virtual cards as I'm having a clear out.

## **Describe alternatives you've considered**
I could always just be more careful - but that doesn't sound much like me

## **Additional context**
Utinni!

**Comment by jokerking16** [comment]
I think changing the format drop-down menu to Open (no v-cards) would accomplish what you are seeking.

**Comment by ideatrack** [comment]
It does - User Error on my part! Thanks JK. I'll close this.
