### ISSUE TITLE
Commander Luke in Rogue 1 and Dash in Rogue 12 Interaction

### ISSUE THREAD

**Issue by egee112** [PlayersCommittee/gemp-swccg-public#408]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**

If one elects to use Dash in Rogue 12s' game text to draw two destiny and choose 1 in conjunction with Commander Luke - who draws two battle destiny if not able to otherwise, you will only draw 1 destiny after making your choice via Dash. 

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
As weird as it is, this is how the rules say to handle this situation: https://forum.starwarsccg.org/viewtopic.php?f=5&t=65850&p=1185889
