### ISSUE TITLE
•Eee Chu Wawa! - Used or Lost Interrupt being lost when playing as a Used Interrupt

### ISSUE THREAD

**Issue by Steveington** [PlayersCommittee/gemp-swccg-public#411]
## **Describe the bug**
•Eee Chu Wawa! - A Used or Lost Interrupt.  It was played as a Used Interrupt (to subtract 2 from forfeit) but was lost after being played.  

SteveG initiates playing •Eee Chu Wawa! from hand
SteveG plays •Eee Chu Wawa! from hand to reduce •Major Panno's forfeit by 2
SteveG reduces •Major Panno's forfeit by 2 until end of the turn using •Eee Chu Wawa!
SteveG puts •Eee Chu Wawa! in Lost Pile

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=SteveG$xug85oae67jgh2ob
SteveG Turn #3

## **Expected behavior**
I expect it to be a used interrupt and go to used pile

Thank you!

**Comment by EchoBaseTrooper** [comment]
Fixed in the latest release
