### ISSUE TITLE
Rescue in the Clouds V causing BD to be drawn if unable to for both sides

### ISSUE THREAD

**Issue by jedimaster03** [PlayersCommittee/gemp-swccg-public#412]
- [ X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
During battle, both sides have less than 4 ability.  LS played Rescue in the Clouds V and both LS and DS were able to draw BD.

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jediMT$ph9i3o23yc0w4qf0

LS turn 6.

## **Expected behavior**
Rescue in the clouds should only allow LS to draw BD if unable to otherwise.

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
