### ISSUE TITLE
Tobias Beckett's destiny not counting for Kessel run total when Han... Solo is on the table

### ISSUE THREAD

**Issue by BrenDerlin** [PlayersCommittee/gemp-swccg-public#414]
I was drawing destinies for Kessel Run and GEMP counted Tobias Beckett's destiny as 3 when it was drawn, but after my total got to 15, GEMP drew another destiny to bring the total to 18. I bet once the card's stacked on Kessel Run it's not currently being "drawn for destiny" so GEMP treats his destiny as 0 when checking to see if it should draw another destiny. 

Replay code here, it takes place in the Light player's second deploy phase : BrenDerlin$75dhswvge3hfeg50
I'm on the Unity web beta in Firefox on a Windows 10 Pro machine, if it matters.

**Comment by EchoBaseTrooper** [comment]
This is working as intended based on this response from the rules team: https://forum.starwarsccg.org/viewtopic.php?f=5&t=76775&p=1321961&p1321961
