### ISSUE TITLE
When inserting a card, note in the chat when the deck is shuffled

### ISSUE THREAD

**Issue by exmultipass** [PlayersCommittee/gemp-swccg-public#418]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes
## **Describe the bug**
My LS opponent inserted Never tell me the Odds into my reserve deck on their first turn.  My deck had around 45 cards in it. On my very next turn (turn 2), after activating 5 force, Never Tell me the Odds reached the top and I was forced to lose force. My reserve deck was never shuffled and no other cards were played during their turn, or at the beginning of my turn.
## **To Reproduce**
I have not had a chance to reproduce behavior, it might have just been this one game.

## **Game Replay ID:**

Multipass$ran738winjue2yg2
## **Expected behavior**

The Effect should have taken several turns before reaching the top
### **Desktop (please complete the following information):**
GEMP

**Comment by EchoBaseTrooper** [comment]
This is not a bug. The rules state
>"Insert" is defined as: the act of sliding a card face down into your opponent's Reserve Deck (or face up into your own), then reshuffling.

You got unlucky that it was shuffled towards the top of your deck, but that will happen sometimes.

**Comment by exmultipass** [comment]
That's interesting because every other insert card that _I_ have played always starts on the bottom, and then has to slowly work it's way to the top. I've never heard of shuffling the insert card in.  If you have any control over GEMP, it might be helpful to put a text line in the chat that states the insert cards is being shuffled in, rather than being place on the bottom (like the used pile). Thanks

**Comment by EchoBaseTrooper** [comment]
That's a good idea.

**Comment by EchoBaseTrooper** [comment]
This is included in the latest release
