### ISSUE TITLE
Stunning leader didn't work at the JP Entrance cavern

### ISSUE THREAD

**Issue by cringwell** [PlayersCommittee/gemp-swccg-public#419]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
He battled me at the entrance cavern (interior/exterior site) and stunning leader was not allowed to be played.

## **To Reproduce**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=advocate$ztydk9b971wkl95v

Turn 8 he battled me.

**Comment by EchoBaseTrooper** [comment]
GEMP didn't let you play it because of the implied target rule. There were no characters of ability > 2 or leaders participating in the battle.

**Comment by cringwell** [comment]
Thanks. Sorry about the mess :)
