### ISSUE TITLE
Neb Dulo - can not utilize full game text

### ISSUE THREAD

**Issue by IwantBasse** [PlayersCommittee/gemp-swccg-public#420]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
- [ ] YES, I did not find anything when searching for his name.

## **Describe the bug**
Text on Neb Dulo:
"When a battle was just initiated where present, may choose one opponent's character of ability <X to move away for free (or that character is lost), where X is your number of musicians present."
Did not get the chance to use his ability as a just response.

## **To Reproduce**
Have Neb Dulo with two other musicians in a battle. One of the dark side characters have to have ability 1 or 0. It should come up as a "Just initiaded" response to the battle being initiated.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Basse$4qcpgul4pilk5iwq
Light side, turn 2, battle at tatooine:jabbas palace.

## **Expected behavior**
At the start of the battle, I wanted Neb Dulo to light up, if I wanted to use his ability as a just response to the initiation of the battle. He was with two musicians, Oola and Jess.

## Client Platform
no idea

**Comment by EchoBaseTrooper** [comment]
This wasn't permitted because there wasn't a site for the character to move to.

The AR says
>A card cannot be targeted by any action that includes moving away (or relocating to an adjacent site) if there is no legal location to move to.
