### ISSUE TITLE
Don't Forget the Droids was able to cancel DS battle destiny while set 13 Maul on table.

### ISSUE THREAD

**Issue by flaminmonkee** [PlayersCommittee/gemp-swccg-public#421]
## **Describe the bug**
LS Don't Forget the Droids interrupt was able to cancel DS battle destiny while set 13 Maul on table.  Maul's text should have prevented this as it states "Opponent may not cancel your destiny draws."  See gemp chat log in below screenshot and replay.  

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=noreply$7ejqhuncn72dj64p

Battle occurred on DS noreply turn #4.  During this battle Solidsnck was able to cancel the battle destiny draw of Sith fury using Don't Forget the Droids.  Set 13 maul was on table which should prevent this.  

## **Screenshots**
![Screen Shot 2021-08-17 at 8 55 20 AM](https://user-images.githubusercontent.com/86481056/129737441-ddccd330-b9e1-4c66-94a4-86673eb36de1.png)

### **Desktop (please complete the following information):**
 - OS: Mac OS High Sierra, version 10.13.6 (17G14042)
 - Browser safari
 - Version 13.1.2 (13609.3.5.1.5)

**Comment by EchoBaseTrooper** [comment]
Should be fixed now

**Comment by flaminmonkee** [comment]
Thanks for all the work on gemp!
