### ISSUE TITLE
DFS-327 modifying deploy costs without battleship

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#422]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
DFS-327 states that "While at same system as your battleship...opponent's pilots deploy +2 to starfighters at this system"

## **To Reproduce**
1. Deploy DFS-327 (without a battleship)
2. Light deploys pilot aboard a starfighter at same system.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jokerking$lve6limtlspbo6e0

Bug occurs on Light Turn 1.

## **Expected behavior**
Poe Dameron and Rogue One deploy for 6, instead of 8.

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
