### ISSUE TITLE
Probe Telemetry - can place out of play more cards then it allows

### ISSUE THREAD

**Issue by Steveington** [PlayersCommittee/gemp-swccg-public#423]
When playing the interrupt, Probe Telemetry, it says to use 2 force to search through a lost pile and put X non-unique cards out of play, where X = # of probe droids on table.  I only had one probe droid but it allowed be to forfeit 3 cards.  See game text below.

SteveG initiates playing Probe Telemetry from hand
SteveG uses 2 Force
SteveG plays Probe Telemetry from hand to search rando_blu's Lost Pile and place 1 non-unique cards out of play
SteveG causes ••Landing Claw, Elom, Elom to be placed out of play using Probe Telemetry
SteveG puts Probe Telemetry in Used Pile

## **To Reproduce**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=SteveG$n8bybn06948d9254
SteveG turn #7 is when this is used.

**Comment by EchoBaseTrooper** [comment]
This should be fixed now
