### ISSUE TITLE
Tallon Roll can target Death Star Assault Squadron

### ISSUE THREAD

**Issue by DSx61x4** [PlayersCommittee/gemp-swccg-public#424]
Tallon Roll is able to target Death Star Assault Squadron, but should not be able to since it is not a starfighter.

I have not tested Dark Maneuvers/Tallon Roll, or any other squadrons.

Test game:
[https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DSx61x4$qu0xjvjuxd0oyz5i](url)

**Comment by EchoBaseTrooper** [comment]
This should be fixed now (for the combo version as well)
