### ISSUE TITLE
Can’t recycle Luke’s Blaster Pistol

### ISSUE THREAD

**Issue by bibfortuna25** [PlayersCommittee/gemp-swccg-public#427]
In a game tonight, Luke carrying Luke’s Blaster Pistol was hit by the Sniper combo and made lost. The gun lit up so I could put it in my Used Pile. But when I lost the required Force, it didn’t go to my Used and the gun lit up again. Ultimately the gun ended up in my lost pile. 

I don’t have a replay handy since we reverted and I chose not to lose the Force to initiate the action a second time.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in latest release
