### ISSUE TITLE
Cloud City Location Deployment

### ISSUE THREAD

**Issue by 19RANGER52** [PlayersCommittee/gemp-swccg-public#429]
- [ Y] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Was watching a game between 
Pmj (LIGHT: Old Allies), ideatrack (DARK: TDIGWATT) on Sunday afternoon.  Noticed that the DS docking bay was allowed to be deployed between an exterior and interior site.  Correct deployment for CC is Ext, LS DB, Int, DS DB.  Game allowed Ext, DS DB, Int.
## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
No, the correct placement is [exterior] [1st docking bay deployed] [interior] [2nd docking bay deployed]
Which side of the force the docking bay comes from is irrelevant. Which one was deployed first/second is the part that matters. See appendix E in the AR.
