### ISSUE TITLE
Eventually You'll Lose behaves like Grimtaash

### ISSUE THREAD

**Issue by Ericobasso** [PlayersCommittee/gemp-swccg-public#431]
As soon as DS has more then 13 cards in hand, Eventually You'll Lose gives the option to put cards back (like Grimtaash). See the provided link for more detail. I've had this in a All of the Jedi league game as well, but reverted, since that shouldn't be possible.

[](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Ericobasso$gi6uxpcalzm1lnfm)

**Comment by EchoBaseTrooper** [comment]
This should be fixed now.
