### ISSUE TITLE
When there is only 1 starfighter attempting the Attack Run, Dark Side player is not able to fire weapons at that starfighter during "Provide Cover" phase

### ISSUE THREAD

**Issue by theeatenpath** [PlayersCommittee/gemp-swccg-public#432]
During game carlosss$n9s8sce1gssz7su2 — the LS player attempted an Attack Run on turn #8.

The only starfighter making the run was Red 5.

During "Provide Cover" phase, DS player attempted to fire two weapons at Red 5, but neither was available to be selected as a "provide cover action." The only option available was "Pass."

When the DS player chose "Pass," the "Provide Cover" phase immediately ended.

It seems the logic is behaving as if there were wingmen on the Attack Run, but there weren't.

**Comment by EchoBaseTrooper** [comment]
This should be fixed now. There were actually two bugs related to this. Thanks for reporting!
