### ISSUE TITLE
Leia Seeker Doesn't Allow DS Player to Pick Lost Character

### ISSUE THREAD

**Issue by TalonJohn** [PlayersCommittee/gemp-swccg-public#434]
Leia Seeker didn't work. When I moved it over to a site that both players occupied, it killed my ability 2 warrior instead of General Leia (the specific DS character was Gamall Wironicc). Unlike the Luke Seeker, it doesn't specify any limitations of which Leia it can kill, and it should be the DS player's choice.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Jmwerner$w0e3h1abw6qqk1l9

**Comment by EchoBaseTrooper** [comment]
The "of ability < 3" applies to Leia as well.

Errata text:
Deploys for 1 Force to an unoccupied site. Deploys and moves like an undercover spy. When present with Leia (or warrior) of ability < 3, choose one to be immediately lost (treat as an "all cards" situation). Seeker is also lost.

**Comment by TalonJohn** [comment]
Wow, really? In 20 years I never heard of this errata. Dang. Ok, thanks for
the response
