### ISSUE TITLE
Master Kenobi communing repeatedly adds to power

### ISSUE THREAD

**Issue by jediosu** [PlayersCommittee/gemp-swccg-public#438]
## **Describe the bug**
Multiple activations of Master Kenobi (use 1 force to add to power) isn't affected by the cumulative rule

## **To Reproduce**
1. Master Kenobi communing
2. Luke in a battle
3. use 1 force to add 5 to power
4. keep doing it until you run out of force or feel good about your power lol

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ashnolo$8oja16chtxlfgf1q
Dark Side battle turn 5 Master Kenobi adds +25 to power when used 5 times

## **Expected behavior**
multiple activations should not result in multiple power additions

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 92.0.4515.159

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
