### ISSUE TITLE
Blown Away DS site has LS back.

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#440]
## **Describe the bug**

Dark Side turn 5:
When the Dark Side Site "Scarif: Citadel Tower" was blown away by the superlaser, it flipped over and showed a LS back even though it was a DS site. 

## **To Reproduce**
1. Use On The Verge 7 side to blow away a site with superlaser/CPI V
2. Click on Scarif: Citadel Tower (with characters from each side ther)
3. Blown Away action occurs correctly

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$zz6sud6fn9zunm6i

## **Expected behavior**
When blown away, the back was expected to display the owner of the site (Dark Side).

**Comment by EchoBaseTrooper** [comment]
This is fixed now
