### ISSUE TITLE
 Kin Kian does not Stay Sharp

### ISSUE THREAD

**Issue by FlorisDeVijfde** [PlayersCommittee/gemp-swccg-public#442]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes, I could not find Stay Sharp! or Kin Kian issues.

## **Describe the bug**
When using Stay Sharp! in the control phase with Kin Kian as gunner I only received +2 to the weapon destiny total, either from Stay Sharp or from Kin Kian. Since Kin Kian is a gunner in his lore I would expect a bonus from Stay Sharp! as well as his own gametext. 

## **To Reproduce**
Use Stay Sharp! in the control phase with Kin Kian as gunner. You only get +2 to your total, either from Stay Sharp or from Kin Kian. 

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=FlorisV$z0if3xpb74crix3u
(LS turn #5, Control Phase)

## **Expected behavior**
+4 to the total weapon destiny, 2 from Stay Sharp, 2 from Kin Kian. But I only got 2 added to the total.

## **Additional context**
Possibly Kin Kian was not implemented as "gunner". Or Stay Sharp! does not function as should with gunners. Kin Kian's bonus to total weapon destiny is not restricted to battle as far as I can see.

**Comment by EchoBaseTrooper** [comment]
Adding 2 is an optional ability so you have to choose to apply it. When the weapon destiny is drawn you have the option to add 2 by clicking on a little Stay Sharp! that appears above your lost pile. The image below is from the replay.
![image](https://user-images.githubusercontent.com/45436940/133106512-cff47ff8-c862-4277-8f4d-5851e2dfa7cd.png)
