### ISSUE TITLE
Rock Couldn't be thrown with no reserve deck

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#443]
## **Describe the bug**
*I'm not positive it's a bug, but I didn't see anything played to prevent me from firing weapons.
LS turn 7 - At Audience chamber, Chewbacca Defender is in battle against Proxima (With a vine snake on her) and 4-lom w/ Rifle. Chewbacca has a rock and Chewie's bowcaster on him, both deployed this turn. No cards in LS reserve deck. LS was unable to throw the rock (or fire bowcaster). Couldn't figure out why. 

## **To Reproduce**
1. Go to LS turn 7
2. Observe battle
3. Weapons didn't light up 
5. See error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$7ectr2m6uslhme5k

## **Expected behavior**
Expected the rock could be thrown (making her power = 0, then competing actions of being excluded and eaten by the snake).

**Comment by EchoBaseTrooper** [comment]
There was a check to make sure the player had a card in reserve deck to be able to fire a weapon. That check is now removed.
