### ISSUE TITLE
Free Ride & Endor Celebration (V) unable to cancel 'react' from hand

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#445]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Dark side deployed Tempest Scout 6 as a 'react' to a battle initiated by Light.  Free Ride combo did not light up as an option to cancel the react.  On a later turn, Free Ride combo was able to cancel a combat vehicle moving as a 'react'.

## **To Reproduce**
1. Initiate battle.
2. Dark deploys with a reacting combat vehicle.
3. Light is unable to play Free Ride combo (V)

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jokerking$d2ln238hjsanw9gu

Light turn 4 (movement react successfully canceled on a later turn)

## **Expected behavior**
All reacts involving a combat vehicle are cancelable with Free Ride combo (V), not just movement reacts.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in the latest release
