### ISSUE TITLE
A Valuable Hostage text in chat log

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#446]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
When A Valuable Hostage performs the Force Pile search, both "force" and "pile" are lower-case.  These should be upper-case to match previous precedent.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in the latest release

If you find any more instances of this let me know. This is one of the easiest possible fixes.
