### ISSUE TITLE
8D8 Not releasing Prisoners

### ISSUE THREAD

**Issue by exmultipass** [PlayersCommittee/gemp-swccg-public#448]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
My opponent had Han imprisoned and 8D8 was on my side. GEMP never allowed me to activate his ability and draw in order to release the prisoner.

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by exmultipass** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Multipass$myz5ha9hc2ftc67x

It wouldn't let me release Han, even during my own turn. Thanks

**Comment by EchoBaseTrooper** [comment]
8D8 can release "imprisoned" captives, not any captive. Captives are "imprisoned" when they are being held inside a prison.
