### ISSUE TITLE
Set 16 Bowcaster deploys for 1. 

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#449]
## **Describe the bug**
Bowcaster (V) deployed for 1 force instead of 0. 

## **To Reproduce**
1. Go to LS Turn 1 - Deploy
2. Dark Side Shield Death Star Sentry on table.
3. LS Card "Wookiee" on table.
4. LS Deploys the card "bowcaster" (Set V16) on wookiee
5. LS used 1 force to deploy the bowcaster.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$o1rszmxj250wcp7o

## **Expected behavior**
Because the default for the bowcaster is to deploy for 0 (no cost listed) the X=1 from wookiee, nor the shield, should have modified the cost. Nothing else on table I noticed. 

## **Screenshots**
![image](https://user-images.githubusercontent.com/72903915/133910020-0d534839-a243-48b8-9af5-c7cfc12e4a69.png)

**Comment by fungineer-86** [comment]
Had a related bug. LS turn 1, deploy. Had no force left, had a "wookiee" and "Wookiee warrior" at a site, and could only deploy the bowcaster (V) on wookiee warrior. 

![image](https://user-images.githubusercontent.com/72903915/133913995-eb2c335a-52ed-489d-91b4-c3acb2b0ea1a.png)

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$z7q85rkhg0zn1fpc

**Comment by EchoBaseTrooper** [comment]
Yeah, the way Wookiee was coded sets the cost of cards named Bowcaster to 1 when they deploy on him. This will be easy to fix.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in the latest release
