### ISSUE TITLE
Disarmed Lost Upon Persona Replacement (should stay with new persona)

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#450]
## **Describe the bug**
Lord Vader was Disarmed.  On a subsequent turn, Dark replaced Lord Vader with Darth Vader, Emperor's Enforcer.  Disarmed went to Lost Pile instead of remaining with the new Vader persona.

## **To Reproduce**
1. Disarm a character.
2. Persona replace that character.

## **Game Replay ID:**
Game replay ID PMed to Adam, since it was a Playtesting game.  Bug occurred on Dark turn 5.

## **Expected behavior**
Disarmed transfers to the new persona instead of checking to see if a weapon is present.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in the latest release
