### ISSUE TITLE
Bog Wing won't attack

### ISSUE THREAD

**Issue by exmultipass** [PlayersCommittee/gemp-swccg-public#451]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
A bog wing was present on Dagobah with two characters that were acceptable targets. Bog Wing never attacked any of the characters and never gave me to option to attack either.

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Multipass$j2n2o6vsimudwtyv

## **Expected behavior**
Bog wing should have attacked. Creature attacks aren't even optional if I recall correctly.

**Comment by EchoBaseTrooper** [comment]
When was this game? This was supposed to be fixed a few weeks ago.

**Comment by EchoBaseTrooper** [comment]
It looks like this game was played 8/20. This bug was fixed 8/31 (see the changelog: https://forum.starwarsccg.org/viewtopic.php?f=964&t=70203)
