### ISSUE TITLE
Possible defect: Trample vs Obiwan

### ISSUE THREAD

**Issue by joe-death** [PlayersCommittee/gemp-swccg-public#462]
https://gemp.starwarsccg.org/gemp-swccg/game.html?gameId=954

Played Trample against Obi Wan Kenobi (ability 6). I had YCHF&Mob Points combo down, which is -1 to jedi defense value. 

I drew a 6. Gemp registered as a failure. 
Trample works against ability. Im not sure if this would change the ability 6 to a 5?

**Comment by bibfortuna25** [comment]
Trample targets ability, not defense value. You need a 7 to step on Obi.
