### ISSUE TITLE
High Speed Tactics and Get Alongside That One don't target transport vehicles

### ISSUE THREAD

**Issue by munchanka** [PlayersCommittee/gemp-swccg-public#463]
High Speed Tactics and Get Alongside That One only target your "piloted" vehicles with maneuver. Cards just say "non-creature vehicles with maneuver." When it comes to opponent's card, it will target any vehicle with maneuver.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=munchanka$spo2p4xruu8krg8c

Seems like this card should allow you to target your "piloted or driven" vehicle with maneuver. In my tests, it only worked on shuttle vehicles and combat vehicles, which require pilots.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
