### ISSUE TITLE
Wookiee Strangle and Cancelled Destinies

### ISSUE THREAD

**Issue by MatthewHT** [PlayersCommittee/gemp-swccg-public#464]
When a destiny draw for Wookiee Strangle is cancelled, that player should have no total and automatically lose.

From Gergall:
I would agree with you that Wookiee Strangle needs a destiny draw in order to add ability and power.  Cancel the destiny, that player has no total and loses.  (Although if both players got canceled I guess both players lose and nothing happens)
This is similar to weapons.  If I have a weapon that hits on destiny + 1 > ability, and my draw is canceled, I still don't hit R2-D2.  I have no total and fail.

Near the end of the game in this replay:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MatthewHT$gk5pyarmpj645psi

**Comment by EchoBaseTrooper** [comment]
Fixed in latest update
