### ISSUE TITLE
Set 12/13 images not showing up

### ISSUE THREAD

**Issue by sokolmatt** [PlayersCommittee/gemp-swccg-public#467]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **To Reproduce**
3. 
4.
5. See error

**Comment by sokolmatt** [comment]
The images for sets 12/13 were not showing up when I logged in. I tried three different browsers.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest update
