### ISSUE TITLE
Jedi Pack added to Merchant

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#468]
## **Describe the solution you'd like**
New users are given the Jedi Pack upon registering, but additional Jedi Packs cannot be purchased.  Individual Jedi Pack cards are available, but this can be cost prohibitive.  I am proposing adding Jedi Pack as a purchaseable item.

The **minimum** cost for such a pack should be 5.50, since that is the amount one would earn for selling the contents back.

**Comment by EchoBaseTrooper** [comment]
This and the Rebel Leader pack are in the merchant now
