### ISSUE TITLE
Toryn Farr revive at different location

### ISSUE THREAD

**Issue by blakesilkwood** [PlayersCommittee/gemp-swccg-public#469]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
Playing No Idea. I initiated a battle at Scarif Vault. I forfeited a character from the battle. Toryn Farr was allowed to revive the character, despite not being at the same location. She was on the Bright Hope up at Scarif.

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**

Battle on my Turn #6
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bsilkwoo$p24ya71g7o8empt2

## **Expected behavior**

Revive should not have been allowed, as she was not at the location where the battle occurred nor the location where the character was forfeited.

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Unknown

**Comment by EchoBaseTrooper** [comment]
Toryn Farr (V) doesn't light up in the replay. That was Commander Vanden Willard (V) "Once per game, may place your just lost Alderaanian in Used Pile."

**Comment by blakesilkwood** [comment]
My mistake Adam. It's hard with all those cards on the ship! I've never
used that Vanden Willard (V) text. Thanks for looking into it.
