### ISSUE TITLE
Darth Vader, Betrayer Of The Jedi

### ISSUE THREAD

**Issue by SWCCGSlade** [PlayersCommittee/gemp-swccg-public#470]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Lore states V16 Vader is a Leader but 'Overseeing it personally' V didnt light up to be able to deploy on Vader. It happend on Darkside turn #2 

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Slade$phh7isrh5q65hdci

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
