### ISSUE TITLE
Boba Fett w/BR not available for Audience Chamber pull while Lyn Me present due to force spend requirements

### ISSUE THREAD

**Issue by modalnode** [PlayersCommittee/gemp-swccg-public#471]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Boba Fett w/BR not available for Audience Chamber pull while Lyn Me present due to force spend requirements even though Lyn Me should convert cost to free

## **To Reproduce**
Deploy Lyn Me to dark Audience Chamber
Use Audience Chamber text to deploy Boba Fett w/Blaster Rifle with less available force than card cost
Boba Fett w/Blaster Rifle not available to select.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=modalnode$6uh30evtep3sc127

## **Expected behavior**
Boba should have free deploy conditions whether from hand or Reserve deck
### **Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Edge
 - Version Version 95.0.1020.53 (Official build) (64-bit)

**Comment by EchoBaseTrooper** [comment]
Your opponent had played the Goldenrod shield which says "For opponent to deploy a character, starship, or vehicle for free (except by that card's own game text), opponent must first use 2 Force."

You did not have 2 Force available.
