### ISSUE TITLE
Spiral react not recognized for FD

### ISSUE THREAD

**Issue by joe-death** [PlayersCommittee/gemp-swccg-public#472]
https://gemp.starwarsccg.org/gemp-swccg/game.html?gameId=1320
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Fire29$wp27w1s2pm1184p2

Opponents Turn 3
Opponent FDed at Ralitir Spaceport docking bay. 

Had Spiral in hand and 2 force in force pile. Spiral is -3 deploy (deploy 5 normally) for a react. 

Gemp didnt recognize to react to the FD. Believe should have been valid.

**Comment by EchoBaseTrooper** [comment]
Spiral is a capital starship. Capital starships cannot deploy to sites.
