### ISSUE TITLE
Cloud City West Gallery allows Aurra Sing w/Blaster to fire at site which is not the "nearest" exterior site

### ISSUE THREAD

**Issue by thomasmarlin** [PlayersCommittee/gemp-swccg-public#473]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
DS Cloud City West Gallery allowed me to fire at a an exterior site which is NOT the "nearest"

## **To Reproduce**
1. Deploy sites as:   [CC West Gallery][CC East Platform Docking Bay][CC Downtown Plaza]
2. Deploy Aurra Sing with Blaster Rifle at the West Gallery (West Gallery allows to fire at nearest exterior site)
3. Battle at the CC Downtown Plaza
4. Aura should not be able to shoot at the Downtown Plaza since the East Platform Docking Bay is the "nearest" exterior site, not the Downtown Plaza

## **Game Replay ID:**

Light Side Turn 5, Battle phase (sdpsc's turn):
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=hyvee$4fliz1kzv2h2g8xc

## **Expected behavior**
Aura should not be able to shoot at the Downtown Plaza since the East Platform Docking Bay is the "nearest" exterior site, not the Downtown Plaza

## **Screenshots**
Note that it indicates in the chat log that Aurra was successfully able to fire at the battle at the Downtown Plaza:
![image](https://user-images.githubusercontent.com/10925599/143661572-b82d46e9-2555-4bbb-862e-9fea43270c40.png)

### **Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version Version 96.0.4664.55

## **Additional context**
(Dark): Cloud City West Gallery Gametext:
"Your blasters present may fire at targets at nearest related exterior site."

Aurra Sing With Blaster Rifle Gametext:
Permanent weapon is •Aurra Sing's Blaster Rifle (may target a character for free; if targeting a Jedi, draw two destiny, otherwise draw destiny; target hit, and its forfeit = 0, if total destiny +1 > defense value)

**Comment by mgutman33** [comment]
I have also encountered this bug. This time it was the light side version of CC West Gallery. Using 'No Questions Asked', Lando With Blaster Pistol was able to fire at an exterior site two sites away from the West Gallery. You can see a reply here:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=SithSev$8o0riyppptl3mdte
It is during the control phase of MPac's third turn.
