### ISSUE TITLE
IT-O [Eyetee-Oh] Drain Bonus Not Working

### ISSUE THREAD

**Issue by DSx61x4** [PlayersCommittee/gemp-swccg-public#474]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
The detention block had five or six captives, but IT-O was not adding to force drain.  Shift clicking on the Detention Block, it said "DS Force Drain 1 (+0 from IT-O)" When I had Presence of the Force deployed on the Detention Block and four or five captives.  

## **To Reproduce**
Place captives in Detention Block and try do force drain with IT-O present.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DSx61x4$wwt40s0n4buc2hoi
(Turn 7 I think)

## **Expected behavior**
IT-O should add X to force drain at Detention Block Corridor where X is number of captives. 

### **Desktop (please complete the following information):**
Windows 10
Google Chrome

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
