### ISSUE TITLE
Game crashed 

### ISSUE THREAD

**Issue by JNapolit31** [PlayersCommittee/gemp-swccg-public#476]
Replay through to the end (DS battle phase turn #4)...

Baze was hit by Maul's Lightsaber, then Sniper/Dark Strike to make him lost mid-battle. He then fired successfully with his gametext upon going lost, and then game crashed.

"Game was cancelled due to an error, the error was logged and will be fixed soon.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay?

**Comment by JNapolit31** [comment]
Yikes. Sorry! Here it is. 
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jnapolit31$agw3sbdwdj5um944

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
