### ISSUE TITLE
Beta UI: Artwork not loading on many cards, showing card backs instead

### ISSUE THREAD

**Issue by CelestialSix** [PlayersCommittee/gemp-swccg-public#479]
- [ yes ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Artwork images not loading on many cards, showing image of LS or DS card backs instead

## **To Reproduce**
1. Play game in the Beta UI
2. Upon set up and deal, 3 to 5 cards in total show card backs instead of their artwork

### **Desktop (please complete the following information):**
 - OS: Mac OS BigSUR 11.6
 - Browser [chrome]
 - Version [Version 96.0.4664.93 (Official Build) (arm64)]

**Comment by fungineer-86** [comment]
I was having this same issue when trying to watch a replay. Tried a couple different games including this one. Though it seems I may have gotten 1 or 2 more cards loaded when I re-tried the link, over half were hidden.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$tz140um5s1wgkcpd

Desktop - Google Chrome. 
PC - WIndows 10

**Comment by DevoKun** [comment]
Issue resolved
