### ISSUE TITLE
Auto game cancellation bug - Old Allies - Munica - Graveyard of Giants

### ISSUE THREAD

**Issue by geeroma** [PlayersCommittee/gemp-swccg-public#480]
In Old Allies, Munica, a resistance character, denies opponents force retrieval from Graveyard of Giants. 

Every time this action is triggered the game auto crashes. This bug very severe and hinders to PC's committee's 
card to see any play online. Please please take a look at this. 

dark side, last turn. 

[https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BSF$l4392864zkobl9ei](url)

Thanks in advance.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
