### ISSUE TITLE
Formatting in game chat log when using Plo Koon (V) text

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#481]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Chat log states: Player targets to make a character (or ep-1 starfighter) forfeit +2 and immune to attrition for remainder of turn using Plo Koon (V).

To make it look "prettier", I would recommend changing this to: Player targets to make a character (or [Episode I] starfighter) forfeit +2 and immune to attrition for remainder of turn using Plo Koon (V).

## **Screenshots**
![Plo](https://user-images.githubusercontent.com/71087753/146721586-0a4ba64f-d26c-4268-b3d9-fd2cf47572b8.JPG)

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
