### ISSUE TITLE
Incomplete note in chatlog for Lando Calrissian (V)

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#482]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
When Lando Calrissian (V) is deployed, LS has the option to take into hand (from Reserve Deck) a character with "Cloud City" **in lore**.

The message in the chatbox to reflect this action is incomplete: Player initiates •Lando Calrissian (V) optional response
Player targets to take a character with 'Cloud City' into hand from Reserve Deck using •Lando Calrissian (V)

The message should indicate that the "Cloud City" must come from lore.

## **Screenshots**
![image](https://user-images.githubusercontent.com/71087753/146722260-c240e798-6b7e-4310-84a5-b44c309cdba0.png)

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
