### ISSUE TITLE
Gungon Warrior

### ISSUE THREAD

**Issue by sokolmatt** [PlayersCommittee/gemp-swccg-public#496]
Hello, Gungon Warrior did not deploy -1 to a site the opponent occupied.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Datalar$t41t555hooprl49t
Happened on Light Side's last turn of the game

**Comment by EchoBaseTrooper** [comment]
The Gungan Warrior was also deploy +1 from Naboo (V).

**Comment by sokolmatt** [comment]
Thank you and sorry!
