### ISSUE TITLE
Alien Mob (and it's mirror) will light up each time you retrieve a card (its supposed to be once per turn per copy).

### ISSUE THREAD

**Issue by cringwell** [PlayersCommittee/gemp-swccg-public#498]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=advocate$jh1l0wkmo9sovcuq

Turn 5 control phase and Turn 5 battle phase it lit up for all 3 retrieval.

![image](https://user-images.githubusercontent.com/40776553/149452244-01ad3a34-21d5-4961-96b6-7dbb14ee29fb.png)

- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Should be fixed in latest release
