### ISSUE TITLE
Unable to read chat box

### ISSUE THREAD

**Issue by fungineer-86** [PlayersCommittee/gemp-swccg-public#500]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
When in a game or gemp lobby, I am unable to see what I write in the chat box. Both the box and the text appear white. I can highlight the text and the negative is visible. Once I hit enter, it displays normally in the logs. No other sites/text entry bars are doing this.

## **To Reproduce**
Can only be reproduced on my machine(s).

-Go to lobby, or game chat, type...

## **Game Replay ID:**
(https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fungineer$eizjlytot9z3cf00)

## **Screenshots**
![image](https://user-images.githubusercontent.com/72903915/149610407-6ab0be94-03ba-45aa-ad3d-c034dcc7c58f.png) ( I typed "hi")
![image](https://user-images.githubusercontent.com/72903915/149610416-d8348480-e038-455d-85e0-ba4d61b3cbfc.png) After pressing enter

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 -  Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by fungineer-86** [comment]
I will say, though this happened to me for a few days, it no longer seems to.

**Comment by EchoBaseTrooper** [comment]
If it comes back let me know
