### ISSUE TITLE
Qi'ra Top Lieutenant (dark Qi'ra) does not have "Crimson Dawn" characteristic

### ISSUE THREAD

**Issue by waddenmw** [PlayersCommittee/gemp-swccg-public#501]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Qi'ra Top Lieutenant (dark) does not have the "Crimson Dawn" characteristic

## **To Reproduce**
See dark side first turn, crimson dawn blaster deploys for 1 instead of being free, when examining the Qi'ra Top Lieutenant card, she does not have the "crimson dawn" characteristic like Maul has (he was deployed turn 3 and does properly have this characteristic), despite "crimson dawn" being in her lore.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=timeyouppi$1bdm33jo3ratr6r6
see dark side first turn

## **Expected behavior**
Qi'ra Top Lieutenant was expected to have the "crimson dawn" characteristic, but did not. The Crimson Dawn Blaster cost 1 force to deploy on her (with she being the only character on table) instead of being free.

## Client Platform
Chrome

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
