### ISSUE TITLE
You Swindled Me / Either Way You Win forcing activation

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#503]
## **Describe the bug**
When playing You Swindled Me / Either Way You Win and the activation option is chosen, both players are not given the option to activate 0 Force.  Based on the rules forum post (https://forum.starwarsccg.org/viewtopic.php?t=79990) this is a bug.

## **To Reproduce**
1. Play You Swindled Me
2. Opponent chooses activation
3. Popup box asking you to activate 1-4 Force

## **Expected behavior**
1. Play You Swindled Me
2. Opponent chooses activation
3. Popup box asking you to activate 0-4 Force

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
