### ISSUE TITLE
<>Alien Rabble does not appear to register as non-unique Alien

### ISSUE THREAD

**Issue by blakesilkwood** [PlayersCommittee/gemp-swccg-public#504]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
Playing Agents in the Court, deployed <>Alien Rabble to a third battleground to flip my objective (secondary condition). Objective did not flip. Playing a three-dot alien in a later turn did allow a flip condition.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bsilkwoo$mbgxkdvqztvzdy4g
Issue in question happens on LS Turn #3 
I do flip a turn or two later with a three-dot mando.

## **Expected behavior**
Since <> Alien Rabble is considered a non-unique alien as a member of your species, deploying them to a third battleground should flip your objective. I saw no interactions that would make my 3 sites non-battlegrounds. I do have underworld contacts on a site, but that shouldn't make a site a non-BG (like Bo Shuda definitely does).
https://forum.starwarsccg.org/viewtopic.php?t=79989

## **Screenshots**
Screenshots attached.

### **Desktop (please complete the following information):**
-Windows 7, Chrome

## **Additional context**
![OBJ Flip](https://user-images.githubusercontent.com/94271296/149808690-e0b7ed4c-4f37-4ef7-a9f8-6951186d0350.png)
![OBJ did not flip](https://user-images.githubusercontent.com/94271296/149808702-dc23a0e5-0b9b-48e7-bfaf-e48ce6e86a6e.png)

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
