### ISSUE TITLE
Landing Claw and New Piett

### ISSUE THREAD

**Issue by Rambows123** [PlayersCommittee/gemp-swccg-public#505]
Landing Claw was still able to attach onto the Executor with the new Piett that states that the Landing Claw cannot attach.  

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Rambows$isqhsczkmhxc56gy

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release (and will result in an errata to Admiral Piett (V))
