### ISSUE TITLE
Option to change the game background

### ISSUE THREAD

**Issue by forrest319** [PlayersCommittee/gemp-swccg-public#506]
## **Is your feature request related to a problem? Please describe.**
As a GEMP streamer, I want a solid background, so that my streams aren't trying compress that dark hive background image and the output isn't full of visual artifacts. 

## **Describe the solution you'd like**
Easiest solution would be to point the background at a different image.  I believe this is the current image you are using on repeat - https://gemp.starwarsccg.org/gemp-swccg/css/dark-hive/images/ui-bg_loop_25_000000_21x21.png
A solid color background, some shade of grey or whatever would probably be good.  A more complex solution would include adding a setting of some sort to the user settings to swap between dark-hive or a solid background.  

## **Describe alternatives you've considered**
Learning CSS injection and 'replacing' the image on my local machine. It's beyond what MySpace HTML taught me.

## **Additional context**
I just started watching some streams during the Outrider cup.  You can really see that both Twitch and YouTube struggle with the compression of the GEMP dark hive background pattern.  Lots of visual artifacts.  I think stream quality would improve for everyone if there was a more streamer friendly background.

**Comment by DevoKun** [comment]
Pull request submitted.

**Comment by DevoKun** [comment]
@forrest319 , this feature is now live in gemp.starwarsccg.org!

**Comment by forrest319** [comment]
Awesome. Wasn't sure the ER would actually be worked on and I appreciate
it. Now you got my PM mind thinking about what other stories I can
write.  🤔
