### ISSUE TITLE
Bluff drain not working

### ISSUE THREAD

**Issue by laforge27** [PlayersCommittee/gemp-swccg-public#507]
DS turn #3, player was only able to drain for zero at Tatooine: Bluffs. 
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=oboe-wan$fwwfs0xtq9hj8qq0

**Comment by laforge27** [comment]
I suppose I should add that the player was never able to drain for more than zero throughout the game. I only referenced the first instance of it in my post.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
