### ISSUE TITLE
Turn Start/End Sounds

### ISSUE THREAD

**Issue by CelestialSix** [PlayersCommittee/gemp-swccg-public#509]

**Comment by DevoKun** [comment]
@CelestialSix , please provide more details about what you are requesting. There is not enough information to understand the intent from the title alone. Please add the details and re-open the ticket at that time.

**Comment by CelestialSix** [comment]
“hot keys” beyond shift clicking on cards would be awesome. return/enter to
select, arrow keys, etc.
