### ISSUE TITLE
Failure at the Cave shield does not allow placing cards in used pile when Shocking Information & Grimtaash is played

### ISSUE THREAD

**Issue by jpshiffler** [PlayersCommittee/gemp-swccg-public#510]
## **Describe the bug**
The Failure at the Cave defensive shield is supposed to allow the Dark Side player to place cards in their hand if Grimtaash is played, but it did not appear to allow that response to happen when the lost function of Shocking Information and Grimtaash was played.

## **To Reproduce**
1. As Dark Side player, have duplicates in hand, and have the Failure At The Cave defensive shield on table.  
2. Light Side plays Shocking Revelation & Grimtaash
3. Dark Side player's hand is revealed and duplicates are placed in lost pile without Dark Side getting a chance to put up to two cards in used pile.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Tarelion$7n1ed3ppqxops8nf
Happened twice during the game, once on turn 3 and again on turn 5.

## **Expected behavior**
I expected the Failure at the Cave card to light up after Shocking Information & Grimtaash revealed the Dark Side player's hand, but before duplicates were placed in Lost Pile. The card did not light up, and I did not have any chance to place duplicates in lost pile.

## **Screenshots**
N/A

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 97.0.4692.99

## **Additional context**
N/A

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
