### ISSUE TITLE
B'omarr Monk should only cancel text at Tatooine Jabbas Palace

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#512]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
YES

## **Describe the bug**
AR App B states that B'omarr Monk only cancels the DS text of Tatooine: Jabbas Palace. However, it canceled my DS text at Audience Chamber.

## **To Reproduce**
1. Deploy a B'omarr Monk to Jabba's Palace Audience Chamber.
2. It cancels the text, but it shouldn't.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Gergall$sm32lo76nzbr1q4h
Bug is seen on LS Turn 1.

## **Expected behavior**
Game text should not be canceled.

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/152471254-1fc2e8ca-d5c5-4de8-a3f0-1245dadeddd7.png)
![image](https://user-images.githubusercontent.com/6243118/152471297-97799401-3b03-4a00-9289-ffda572973aa.png)

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
