### ISSUE TITLE
Chewbacca, Defender of Kashyyyk is not pulled by life debt

### ISSUE THREAD

**Issue by Bottman2p** [PlayersCommittee/gemp-swccg-public#513]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
I was defending a battle with Han, alone, and my opponent battled me; this triggered Life debt from my hand and when it pulled up my reserve deck, Chewbacca, Defender of Kashyyyk was present but not deployable/able to be chosen

## **To Reproduce**
See above.  No error presented.

## **Game Replay ID:**
[](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Bottman2$rpkyi7pl2k31okro)

## **Expected behavior**
Chewbacca should be allowed to be deployed, for free, from reserve deck with a trigger of life debt

## **Screenshots**
None

### **Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Google Chrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

### **Smartphone (please complete the following information):**
 N/A

## **Additional context**
the professor shield was not played

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by EchoBaseTrooper** [comment]
It looks like this was the same replay from the other report. Imperial Detention was on the table and you didn't have 2 Force to deploy Chewie.
