### ISSUE TITLE
Artoo and Threepio should not add 2 power to the Millennium Falcon

### ISSUE THREAD

**Issue by Bottman2p** [PlayersCommittee/gemp-swccg-public#514]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
In a game I was playing I made Artoo and Threepio a pilot of the Millennium Falcon.  This added 2 to power of the Falcon.  This should not be the case as they are pilots but add no power as pilots

## **To Reproduce**
No error, see above

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Bottman2$rpkyi7pl2k31okro

## **Expected behavior**
Add nothing to any starship they pilot

## **Screenshots**
None

### **Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Google Chrome
 - Version  97.0.4692.99 (Official Build) (64-bit)

### **Smartphone (please complete the following information):**
N/A

## **Additional context**
None

**Comment by EchoBaseTrooper** [comment]
It was power +2 from Chewie and power +2 from Kashyyyk.
