### ISSUE TITLE
Bright Hope and 0 total battle destiny

### ISSUE THREAD

**Issue by MatthewHT** [PlayersCommittee/gemp-swccg-public#516]
Bright Hope seems to not trigger if the total battle destiny is zero (but defined). The implied targeting rule says there needs to be a power total and an attrition total, but those totals can be zero.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Ryder$ji7l0y2eendyq7c9

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
