### ISSUE TITLE
Mara Jade Persona Issue?

### ISSUE THREAD

**Issue by MrFromMars1** [PlayersCommittee/gemp-swccg-public#519]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Starting on LS turn 4, LS is no longer able to deplay Mara Jade. This is after DS has deployed Mara Jade in ship.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MrFromMars$dorod6i2ndbjnraf

## **Expected behavior**
Since the card titles are different, LS should be able to deplay Mara Jade.

### **Desktop (please complete the following information):**
Windows, Chome

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
