### ISSUE TITLE
Keir Santage only adding 1 instead of 2 to the power of ships he pilots

### ISSUE THREAD

**Issue by JozsefJK** [PlayersCommittee/gemp-swccg-public#521]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **To Reproduce**
1. Deploy keir on a ship
2. Click on the ship to display its stats
3. see "power +1 from Keir Santage"

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=JozsefJK$mkp7xf4p1nadjpqm

## **Expected behavior**
Expected "power +2 from Keir Santage" to ships he pilots
## **Screenshots**

![KeirAdding1](https://user-images.githubusercontent.com/99996254/154761199-6b665de8-6778-4e8e-9a62-de015f64e899.JPG)

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
