### ISSUE TITLE
EPP 4-LOM and EPP 4-LOM (V) perm weapons are considered "blasters" but shouldn't be

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#522]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes I did!

## **Describe the bug**
When 4-LOM With Concussion Rifle (both V and non-V) fire their permanent weapon, it can be re-targeted by Blaster Deflection. This is presumably because GEMP thinks their permanent weapon is a blaster (it shouldn't be).

## **To Reproduce**
1. DS fires EPP 4-LOM's perm weapon at EPP Luke
2. EPP Luke is able to play Blaster Deflection

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS1$og7cz6jpz3h6pb58
EPP 4-LOM (V) gets Blaster Deflection used against him on LS turn 3.
EPP 4-LOM non-V gets Blaster Deflection used against him on DS turn 5.

## **Expected behavior**
Blaster Deflection should not be allowed against these permanent weapons.

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/154772451-b4a8e555-d4dd-43a0-a8dd-2e1eade10b9a.png)

## **Additional context**
Just a bit of good news - the Dagobah weapon card is not allowing Blaster Deflection, which is correct.  So that's nice!

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
