### ISSUE TITLE
Rey All Of The Jedi shouldn't be allowed to pick Luke against BHBM

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#526]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes.  There is another open Rey AOTJ bug but this one is different.

## **Describe the bug**
When Rey All Of The Jedi selects 2 cards from Lost Pile, she should not be allowed to choose Luke if playing against Bring Him Before Me.  Currently, GEMP is allowing her to do it.

## **To Reproduce**
1. Have DS use BHBM
2. Have Luke and another card in Lost Pile
3. Initiate Rey's action to choose 2 cards
4. LS is able to select Luke as one of the cards.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS2$fe1w4pnaicyg3lm3
Bug can be seen on LS Turn 3 and again on LS Turn 4.

## **Expected behavior**
Rey should not have been able to choose Luke.

## **Screenshots**
From LS Turn 4 of the replay above:
![image](https://user-images.githubusercontent.com/6243118/155471259-3a384e10-dad2-477f-8c50-bff5551dc567.png)
![image](https://user-images.githubusercontent.com/6243118/155471274-6e0c4bec-4d7c-4045-ab09-f2f3dcb6c333.png)

## **Additional context**
https://forum.starwarsccg.org/viewtopic.php?p=1369284#p1369284
There may have been a miscommunication during the card's initial GEMP development / during the proofing process. If more information on that is desired message me (Gergall) on Slack.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
