### ISSUE TITLE
Accelerate not properly targeting Flare-S Racing Swoop

### ISSUE THREAD

**Issue by JediJer** [PlayersCommittee/gemp-swccg-public#527]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Accelerate is not a valid play when a driven swoop is on table

## **To Reproduce**
1. Deploy Flare-S Racing Swoop and any valid driver
2. Try to play Accelerate

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jedijer$0s88unvgf1pt1dh3
Should have been able to play it anytime after deploying the swoop on turn 9

## **Expected behavior**

You should be able to target any driven swoop with Accelerate. It is likely looking for a swoop driven by a biker scout.

**Comment by Gergall** [comment]
For the replay, if you don't want to wait until turn 9 to see the bug, I made a replay where the whole deck is swoops and accelerates and drivers.  I could not play Accelerate.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS1$e9vwlxxzdxvqd7am

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
