### ISSUE TITLE
Corellia Operative card not recognized for having ability and ignored by Local Uprising objective

### ISSUE THREAD

**Issue by pvpanzershrek** [PlayersCommittee/gemp-swccg-public#528]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue? YES
## **To Reproduce**

![Operative fail](https://user-images.githubusercontent.com/100497217/155863343-7d675088-3dc7-4ea4-bd54-2c15c69970bb.jpg)

3. 
4.
5. See error

### **Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Chrome
 - Version ?

**Comment by EchoBaseTrooper** [comment]
This is working correctly. Here is the relevant section from the rules:

**Operatives**
Operatives are identified by their title, X Operative, with X being a system. The operative is considered a 'matching operative' for system X (e.g., Kiffex Operative is a matching operative for Kiffex).
Operatives are restricted by special rules as follows:
• You may not voluntarily deploy or move your operative to (or through) a location on its matching planet where you already have an operative (even if inactive) of the same card title.
• If, at any time, two of your Operatives (even if inactive) of the same card title are at the same location on their matching planet, you must choose one to be lost (you may choose an inactive operative to be lost).
• Your operative character on its matching planet may not apply its ability toward drawing battle destiny. Your operative may not control a location on its matching planet for any reason unless you have other cards there capable of controlling the location (e.g., an ability-1 character or a battle droid). Your operatives still occupy that location (and may battle or be battled), but may not Force drain or flip an objective alone.
