### ISSUE TITLE
Qui-Gon Jinn, Serene Jedi added +1 from redrawn weapon destiny

### ISSUE THREAD

**Issue by chrknudsen** [PlayersCommittee/gemp-swccg-public#529]
## **Describe the bug**
Qui-Gon Jinn, Serene Jedi should only add +1 to total battle destiny for completed weapon destiny draws, but he also added for one that was redrawn with Jedi Levitation (V).

## **To Reproduce**
Redraw a weapon destiny while Qui-Gon Jinn, Serene Jedi alone in battle.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=chrknudsen$tk65uq623jar79fy
Light side turn 2, battle phase.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
