### ISSUE TITLE
Agents In The Court fails to adjust the Bo Shuda + Trap Door interaction

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#538]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes, I have checked for it.

## **Describe the bug**
Bo Shuda protects LS Aliens from Trap Door, which is working fine. Agents In The Court is supposed to undo that protection, but it doesn't.  LS remains protected even though they should be vulnerable.

## **To Reproduce**
1. LS must be playing Agents In The Court.
2. Put a LS Alien at Audience Chamber with Bo Shuda there.
3. LS Aliens are protected from Trap Door (so far so good).
4. DS deploys Rancor Pit and a Rancor there.
5. Per Agents In The Court, the LS Aliens should lose their Trap Door protection, but they don't.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DevoKun$pokefspkiks4ce4b

## **Expected behavior**
DS should be able to play Trap Door targeting an LS Alien.  In the GEMP replay above, turn 10, DS plays Trap Door but is only able to target their own character.

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/161135618-c42e2206-b093-4ead-8655-985cdcbe68fd.png)
![image](https://user-images.githubusercontent.com/6243118/161135523-1e4525ea-dec7-4bf0-9c1a-371e54eab49b.png)
![image](https://user-images.githubusercontent.com/6243118/161135636-739a12ea-b3b5-470c-99bd-835b2afae385.png)

## **Additional context**
If I may play junior detective. Looking at the screenshots I have provided, it appears the programmer added the property "Immune to Bo Shuda." to the Trap Door card. And that's a nice note to have, but it seems that it also needs remove the "May not be targeted by Trap Door." from the LS Aliens.

This situation arose note from testing but from actual gameplay in a "jawas and droids only" casual game.

**Comment by EchoBaseTrooper** [comment]
Should be fixed in latest release
