### ISSUE TITLE
Anakin's Podracer and Artoo in Red 5

### ISSUE THREAD

**Issue by deadbody55418** [PlayersCommittee/gemp-swccg-public#540]
When Anakin's racer has Artoo in red 5 stacked on it, even if I select it as a 7, it makes the total zero.  When I had 2 copies of it stacked on there it still allowed me to draw 3 as if I was behind, even though I should have been ahead 14 to 13.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay link?

**Comment by deadbody55418** [comment]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=deadbody$w188jr4rjdqe5itl

there was a revert to switch the order of how I stacked the cards, but it still read my total as zero

**Comment by MatthewHT** [comment]
Another replay with the same bug: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MatthewHT$9pkd8acjcrn2et2p
