### ISSUE TITLE
Hit Racer

### ISSUE THREAD

**Issue by MatthewHT** [PlayersCommittee/gemp-swccg-public#541]
I never had the opportunity to play Hit Racer. This might be related to the R2 in Red 5 bug, though there were times when I was within 4 of his total counting R2 as 0, and within 4 counting R2 as 7, and at neither time could I play Hit Racer.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MatthewHT$9pkd8acjcrn2et2p

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
