### ISSUE TITLE
Captain Han Cancels Flawless Marsmanship?

### ISSUE THREAD

**Issue by ckroutil** [PlayersCommittee/gemp-swccg-public#542]
## **Describe the bug**
I played Flawless Marksmanship to add to a tractor beam draw. Captain Han then canceled this draw.  On the Re-Draw, nothing was added to the destiny from Flawless Marksmanship. 

## **Game Replay ID:**
(https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ckroutil$mc24yhv6zsf1sd1p)

This occurred on Light Side Turn #5 Battle Phase

## **Expected behavior**
I expected Flawless Marksmanship to add 4 to the  re-drawn destiny after Captain Han had canceled the first.

**Comment by EchoBaseTrooper** [comment]
This is not a bug. See this post: https://forum.starwarsccg.org/viewtopic.php?p=917199#p917199
"Flawless Marksmanship only adds to a single specific draw. If that draw is then canceled and redrawn, Flawless Marksmanship won't affect the new draw."
