### ISSUE TITLE
A Good Blaster at your Side combo not downloading unique blasters

### ISSUE THREAD

**Issue by BrenDerlin** [PlayersCommittee/gemp-swccg-public#544]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

yes, a search of "blaster" did not turn up any issues, also this was released only hours ago so it's possible we were the first to notice it.

## **Describe the bug**
My opponent commented that he was unable to deploy matching/unique blasters from reserve deck with the new V18 combo effect, only non-uniques. 

## **To Reproduce**
1. Deploy Luke Skywalker, The Rebellion's Hope to a Death Star site
2. Trigger Good Blaster while Luke's Blaster Pistol (V) and Stolen Stormtrooper Rifle are in Reserve Deck
3. You're able to deploy Stolen Stormtrooper Rifle on Luke, but not his matching blaster.

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BrenDerlin$5erpy6dixjdt0k1k

## **Expected behavior**

The effect specifies the blasters must be non-unique for the ping damage and for deploying from lost pile, but the reserve deck pull only says "blasters" and so unique, matching blasters presumably should also be allowed.

## **Screenshots**

![image](https://user-images.githubusercontent.com/80310974/164510242-491520fc-af42-49e1-93d2-710ae8dcfd51.png)

### **Desktop (please complete the following information):**
Desktop chrome

## **Additional context**
The screenshot and replay link above are from a test game I ran to try to re-create the bug, just to make sure there wasn't anything else wrong (like trying to use Han's blaster v on TK-422) and sure enough the same thing happened. Original game replay is here: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BrenDerlin$vg59jhfzi7mbsy5m

**Comment by EchoBaseTrooper** [comment]
This was noticed quickly and we have a fix ready to go on the next restart. Thank you for reporting it!

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release

**Comment by JediJer** [comment]
Please re-open this bug. It has not been fixed.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jedijer$x7jtoxbwnp4pbirm

Could not deploy Han's Heavy Blaster (non-v) to TK-422 v. It was not an option, however it did allow it to be an option on a subsequent turn (when TK-422 wasn't even on table.

I think that Han's Heavy Blaster Pistol is not recognizing TK-422 v as a persona of Han, or it is using the same logic as Han's Heavy Blaster v, which does not allow you to deploy on spy Han.
