### ISSUE TITLE
Deckbuilder allowing multiple Falcon Junkyard Garbage in 60-card deck

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#547]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes I checked

## **Describe the bug**
It is possible to put multiple copies of The Falcon, Junkyard Garbage into a 60-card deck. However, the AR forbids this when it states "A player may only include one double-sided card of the same title or persona in a deck."

## **To Reproduce**
1. Go to Deck Builder
2. Search for The Falcon, Junkyard Garbage
3.  Place many copies into a deck, along with other cards to reach a 60 card deck
4. GEMP incorrectly states that this is a valid deck for Open and other formats (it says valid in deckbuilder, and GEMP allows it to be used in games)

## **Game Replay ID:**
No replay is required as the issue can be seen in the deckbuilder. I can provide a replay of the deck in action if desired.

## **Expected behavior**
An error message "Deck contains more than one The Falcon, Junkyard Garbage" would be a good error to display.  Similar to what we have for Jabbas Prize

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/164951047-c00390e0-81a2-4cef-9e6c-54a1e9d57e68.png)

## **Additional context**
Let me know if any questions.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
