### ISSUE TITLE
rops not flipping correctly

### ISSUE THREAD

**Issue by thrawn3661** [PlayersCommittee/gemp-swccg-public#549]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

I controlled 3 raltiir sites with imperials and my opponent controlled none but it wasn't until I had imperials at all 4 sites that I slipped. This cost me the game.

## **To Reproduce**
Control 3 raaltiir sites with imperials and occupy 1 site with a walker where the opponent has presence, and the opponent has presence at only that site

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=thrawn3661$xdavhupw1qtvl2l4

## **Expected behavior**
By controlling the 3 sites and occiupying with the vehicle ROPS should flip

**Comment by EchoBaseTrooper** [comment]
Not a bug. Blizzard 8 is not a non-Imperial character. Your total ability was 0 there from Leia, Rebel Princess so your opponent controlled the location.
