### ISSUE TITLE
Wookiee Warrior + Local Defense combo does not work together

### ISSUE THREAD

**Issue by jc725** [PlayersCommittee/gemp-swccg-public#552]
- [yes ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Wookiee Warrior using top level action to restore hit character to normal not working when Local Defense & Put That Down is used as just response on Wookiee Warrior being lost.

## **To Reproduce**
1. Mara Jade w/ Lightsaber in battle vs. Chewbacca Defender + Tarfull + Wookiee Warrior
2. Mara Jade hits Chewbacca.
3. Wookiee Warrior top level action to restore Chewie. As just response to that action, LS plays Local Defense combo to make Wookiee Warrior hit instead.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jc725$phy2an0wxn4rczcn
(LS Turn 5 battle.)

## **Actual behavior**
Chewbacca remains hit. (Wookiee Warrior is also hit, not lost - which is expected.)

## **Expected behavior**
Chewbacca would no longer be hit.

**Comment by EchoBaseTrooper** [comment]
I don't think this is a bug based on this post: https://forum.starwarsccg.org/viewtopic.php?p=1354950#p1354950

The cost for the Wookiee Warrior's ability was never paid (it was not lost), so the result doesn't occur.

Feel free to ask a rules question and reopen this if the answer is different in this case.
