### ISSUE TITLE
Rogue 1 unable to deploy to Naboo (Invasion has cancelled the icons)

### ISSUE THREAD

**Issue by Silverglen** [PlayersCommittee/gemp-swccg-public#553]
Adam - in this game I wasn't allowed to deploy rogue 1 to Naboo - I see no reason why. I have previously been able to.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Silverglen$tr9xiqn5jlg8a5ot

**Comment by jokerking16** [comment]
https://github.com/PlayersCommittee/gemp-swccg-public/issues/499

**Comment by EchoBaseTrooper** [comment]
Duplicate of https://github.com/PlayersCommittee/gemp-swccg-public/issues/499

**Comment by Silverglen** [comment]
Hi AdamDoes this mean we don’t want rogue 1 or tantive deploying to Naboo t1? Or just rogue 1?Thanks Sent from my iPhoneOn 12 Mar 2023, at 00:44, Adam Fletcher ***@***.***> wrote:﻿
Closed #553 as not planned.
