### ISSUE TITLE
Abyss doesn't work for characters on table but excluded from battle

### ISSUE THREAD

**Issue by mtennyson** [PlayersCommittee/gemp-swccg-public#557]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue? YES

## **Describe the bug**
Abyss was on the table. Imperial Barrier was used on Ben Kenobi. A battle ensued anyway. Ben Kenobi was drawn as destiny in the battle, and it wasn't lost or set to 0.

## **To Reproduce**
See above.

## **Game Replay ID:**
See partymcfly's turn #6:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tennymf$8bdpckrzfsjuk8n4

## **Expected behavior**
Ben Kenobi drawn as destiny to be lost and destiny set to 0.

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser: MS Edge
 - Version: Version 100.0.1185.44 (Official build) (64-bit)

## **Additional context**
I asked in Gemp chat and on Discord about this. Several replied saying that Ben was excluded so he was inactive, and because he was inactive, that explains why he wasn't affected by Abyss. However, the rulebook specifically says, "An inactive card represents a card that is in some sense ON THE TABLE." Abyss says, "If a unique card is drawn for destiny and a duplicate is ON THE TABLE." The rulebook says several times that inactive is not the same thing as 'not on the table' in multiple examples. It also says inactive cards still count toward uniqueness. Based on my interpretation of the rulebook, Abyss should still work.

**Comment by EchoBaseTrooper** [comment]
This is not a bug. https://forum.starwarsccg.org/viewtopic.php?p=1126869#p1126869
