### ISSUE TITLE
Best Starpilot In The Galaxy, My Parents Were Strong, The Falcon Junkyard Garbage

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#566]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
My Parents Were Strong should work with Best Starpilot In The Galaxy (player should be allowed to deploy Falcon from there, along with a matching pilot from hand or Reserve Deck).

## **To Reproduce**
1. Deploy My Parents Were Strong and Best Starpilot In The Galaxy
2. Stack Flip Falcon on My Parents Were Strong
3. Attempt to use Best Starpilot once per game action
4. The Flip Falcon on My Parents Were Strong should be included among the cards that are considered to be in hand
5. However it is not included, that is the error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Ericobasso$2g801twac54o3672
To see this bug occur, review the LS Turn 7 Deploy Phase
Player should have been allowed to deploy Solo from Reserve Deck along with Flip Falcon "from hand".

## **Expected behavior**
Flip Falcon would be shown as one of the cards in hand.

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/172982654-ae81ee0f-934c-4a10-965e-5946f5b7a4bf.png)

## **Additional context**
For anyone who may be reading this and curious about the ruling.  The reason Squadron Assignments doesn't work with My Parents Were Strong is because Squadron Assignments needs one card to be revealed (not deployed) from hand, and the other card to be found in Reserve Deck.  My Parents Were Strong doesn't allow the card be revealed as if from hand, only deployed as if from hand.

Best Starpilot however only calls for deployment which is why it should work.  This has been reviewed by the Rules Team and the Design Advocate.  A more formal ruling will also be posted in the near future.

**Comment by crazyrunnerguy** [comment]
Experienced this issue today. LS 3. https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CRG$032jf1py5yeu9kuh

Also, I hate playing against ROPS(V).

**Comment by Gergall** [comment]
Someone told me this is still not working.  I tested it today and I agree.

To make this very easy to review, I put together a replay where you can see the bug on turn 1 and LS goes first!  LS activates 5 force, tries to search hand and reserve deck, and the Flip Falcon is not offered to be deployed with any of the matching pilots in Reserve.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS2$slna0cs67jy0ryf8

**Comment by Gergall** [comment]
I saw in the 8/31 changelog today that it said "fixed interaction with cards that deploy as if from hand"

So I ran more tests:

TEST #1: No matching pilot in hand = Get a failed-to-find message.  Should have been able to use pilot from Reserve Deck.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS2$ald0nm60azp3vdx5

TEST #2: Matching pilot in hand, choose option to search Reserve Deck anyway. Was given a fail-to-find message.  Should have been able to use a pilot from Reserve Deck or even use a pilot from hand after all.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS2$bmavhdun2toee7zo

**Comment by Gergall** [comment]
Tested multiple scenarios and this and looks great!  Tested:
1. Matching pilot in hand, used it.
2. Matching pilot in hand, searched Reserve anyway.
3. No matching pilot in hand, searched Reserve.
4. No matching pilot in hand or Reserve.

All scenarios were successful.  Thanks for putting the time into this to get it working!
