### ISSUE TITLE
Raising a converted site didn't allow me to activate more force

### ISSUE THREAD

**Issue by voxaroth** [PlayersCommittee/gemp-swccg-public#569]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue? **Yes.**

## **Describe the bug**
**At the start of a game, I (DS player) had 5 force icons to start the activation phase.  I had "Rise of the Sith" in my hand, which I played to raise my converted location to the top before activating (location was Bespin system).  The game confirmed at the top that I now had 6 force icons with which to activate, however, when I attempted to activate I was only allowed to activate 5 force.  There were no other cards on table that would have impacted my activation.**

## **To Reproduce**
1. Go to '...' **Start of game, Bespin starting location with Rise of the Sith - Dooku vs QMC.**
2. Click on '....' **Rise of the Sith to raise converted Bespin system to the top.**
3. **Attempt to activate with the extra force icon gained from the conversion.**

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari] **Firefox**
 - Version [e.g. 22] **101.0.1**

**Comment by chrknudsen** [comment]
At the beginning of your turn, your activation is totalled and locked in. After that, the total cannot be altered by stuff like raising a converted location. From the AR, page 3-1:

Activate Phase

The first phase of each of your turns, in which you
activate Force for subsequent use.

• Count the Force icons on your side of each location on
table.
• Add 1 to represent the personal Force you generate
yourself.
• Add 1 for each of your Jedi Masters (for the Light
Side) or Dark Jedi Masters (for the Dark Side).

This total (along with any modifiers to your "total Force
generation") represents the full amount of Force you are
entitled to activate during your Activate Phase for that
turn. This total may not be altered after the count is
completed. The only actions that may affect your total
activation count are those that occur at the 'beginning of
a turn.'
