### ISSUE TITLE
Courage of a Skywalker Seemingly Not Functioning w/ Luke With Lightsaber

### ISSUE THREAD

**Issue by newbrak** [PlayersCommittee/gemp-swccg-public#570]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Courage of a Skywalker Seemingly Not Functioning w/ Luke With Lightsaber. Running through the steps all the way up to choosing whether or not to draw battle destiny, Courage of a Skywalker was not highlighting to signify ability to be played during a battler on Endor Docking Bay, targeting Luke With Lightsaber.

It's like either Courage is not recognizing Luke With Lightsaber as a Skywalker?

## **To Reproduce**
1. Start a battle with Luke With Lightsaber and Obi-Wan With Lightsaber on Endor Docking Bay (this is how it happened when I did it.
2. Initiate battle with Courage of a Skywalker in hand
3. See if Courage is allowed to be played running up through the steps of battle. 

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=newbrak$v8mbdo7tv5lcxl1x

## **Expected behavior**
Expecting to be able to play Courage of a Skywalker; was denied.

## **Screenshots**
Attacked

### **Desktop (please complete the following information):**
 - OSX 15.7
 - Safari
 - Version 15.0

Thank
<img width="1280" alt="Screen Shot 2022-06-15 at 8 21 58 PM" src="https://user-images.githubusercontent.com/107599112/173984218-9e76b415-0444-4979-9e51-2615fad5c06a.png">
!

**Comment by chrknudsen** [comment]
Luke With Lightsaber has no immunity to attrition, so you can't use the first function with him (he has no immunity to lose). And the second function only works during a duel. So this isn't a bug.
