### ISSUE TITLE
Ascension Guns (non-V) with no destiny available led to game cancel

### ISSUE THREAD

**Issue by Pistone84** [PlayersCommittee/gemp-swccg-public#571]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
Game was canceled when my opponent played ascension guns (non-V) and wasn't able to draw destiny as he had activated all of his force.

## **To Reproduce**
1. LS player activate all force
2. Play ascension guns

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Pistone$9mlphk8r69dynsoy

## **Expected behavior**
I expected he would not be able to play the card with no destiny in reserve deck

### **Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Chrome
 - Version 102.0.5005.115

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
