### ISSUE TITLE
Please re-open this bug. It has not been fixed.

### ISSUE THREAD

**Issue by JediJer** [PlayersCommittee/gemp-swccg-public#578]
Please re-open this bug. It has not been fixed.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jedijer$x7jtoxbwnp4pbirm

Could not deploy Han's Heavy Blaster (non-v) to TK-422 v. It was not an option, however it did allow it to be an option on a subsequent turn (when TK-422 wasn't even on table.

I think that Han's Heavy Blaster Pistol is not recognizing TK-422 v as a persona of Han, or it is using the same logic as Han's Heavy Blaster v, which does not allow you to deploy on spy Han.

_Originally posted by @JediJer in https://github.com/PlayersCommittee/gemp-swccg-public/issues/544#issuecomment-1174443371_

**Comment by EchoBaseTrooper** [comment]
Han's Heavy Blaster says "Use 1 Force to deploy on Han, or 3 on your warrior." You had no force available to play it on Han.

![image](https://user-images.githubusercontent.com/45436940/177227343-b90242e5-c9dd-4e8b-9317-65f726fe2d96.png)

**Comment by JediJer** [comment]
yeah, I just realized that. I'm retarded. Used to matching weapons deploying for free
