### ISSUE TITLE
Unity Error whenever Light side Set 18 requested in deck builder

### ISSUE THREAD

**Issue by Decim8or** [PlayersCommittee/gemp-swccg-public#579]
Title is self explanatory.

Screenshot of error message:
![GEMPError](https://user-images.githubusercontent.com/85380361/177468430-72f11de1-722b-4615-ac48-b680930a7536.png)

**Comment by Decim8or** [comment]
Same error seems to be jumping in whenever I try to play a match as well.

**Comment by SWCCGArenaProject** [comment]
Thanks for this report, what's going on is the asset is named as .gif but is actually png data.  Like this for example: https://res.starwarsccg.org/cards/Virtual18-Dark/large/adarktimefortherebelliontarkinsorders.gif

If you download that image and open it in a hex editor is has a png header. Epic duel doesn't understand this mis-naming yet so it's trying to decode that data as gif data but crashes like this.

1.8.5 should be going up in a few days with fix for this.

I appreciate the report, and sorry you had to deal with this for so long.

**Comment by Decim8or** [comment]
Looks like this has been fixed!  Thank you so much!
