### ISSUE TITLE
Solo not adding +2 to DV when OA is flipped and present with charachters & vehicles

### ISSUE THREAD

**Issue by Silverglen** [PlayersCommittee/gemp-swccg-public#580]
As per the title i have noticed in multiple games that this is not happening. I think it might have just been disabled?

**Comment by jdipaolo1** [comment]
@Silverglen We need a little more information and a replay where you are seeing this.
I currently don't see an issue and Han does not work with vehicles:
While with Han, your [Episode VII] characters and [Episode VII] starships are defense value +2.

**Comment by Silverglen** [comment]
Hi
What date did I report this - I’ll go back and check the replay
