### ISSUE TITLE
Add Reflections packs to choice of pack prize

### ISSUE THREAD

**Issue by JediJer** [PlayersCommittee/gemp-swccg-public#583]
Currently, only the non-reflection packs are available options for when you win a "choice of pack" prize from an event or league. 

Would it be possible to add other packs that are not from full Decipher expansions. such as Reflections I, II, III, OTSD/JPSD fixed cards, Rebel Leader, Jedi Pack, EPP, ECC, EJP premiums. It may be nice for some players to be able to collect these, or turn some premium cards into foils cheaper than having to buy all necessary copies for conversion.

While these are available to buy in the merchant, it would be cool if they could also be awarded on occasion, maybe only for certain events/leagues

Additionally, it might be cool if you could spend multiple choices for full EPP, ECC, EJP packs (including the accompanying boosters). If you have a choice of 5 packs, you can 'spend' 3 choices to buy a 'sealed' EPP/ECC/EJP pack, or a Premiere/SE/DSII starter, or even an OTSD/JPSD

I don't know if this would be a separate request, but if the option to 'spend' choices on bigger packs is implemented, would it be possible to bank your choices so that you can save up for the bigger box of packs (I don't know if the currently accumulate if you don't use them, so this part may already be done.

**Comment by jokerking16** [comment]
Reflections I, II, III packs are currently available as prizes.
