### ISSUE TITLE
Bomar Monk when excluded from an offensive battle does not count for civil disorder

### ISSUE THREAD

**Issue by charlesmhickeyjr** [PlayersCommittee/gemp-swccg-public#584]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Bomar Monk when excluded from battle no longer applied to civil disorder, causing the effect to be canceled.

## **To Reproduce**
please see game replay

## **Game Replay ID:**
(https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Teacher$lhiv2vfgwjgymgxn)

## **Expected behavior**
Civil Disorder should remain on table. Civil disorder is a global spot effect.

## **Screenshots**
see replay

### **Desktop (please complete the following information):**
 - OS: ios monteray
 - chrome
 - Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by DSx61x4** [comment]
I believe this is working correctly.  Cards excluded from battle are temporarily inactive and thus not considered to be on the table for the purposes of cards like Civil Disorder.

**Comment by EchoBaseTrooper** [comment]
> I believe this is working correctly. Cards excluded from battle are temporarily inactive and thus not considered to be on the table for the purposes of cards like Civil Disorder.

This is correct. This is not a bug.

**Comment by Gergall** [comment]
Looks like it is a bug as Civil Disorder (and the DS mirror, Ability x3) would fall under the exception where excluded cards should still count for the purposes of keeping cards from being removed from table:

```
Participating In Battle - Excluded From Battle
Excluding a card from battle removes a card from 
participating in the current battle in progress. Cards that 
are excluded from battle are considered inactive for the 
duration of the battle (remember that when a card is 
inactive, then all cards deployed on and aboard it are 
inactive as well); however, being excluded will not
cause objectives to flip or other cards to be canceled or 
otherwise removed from table (these are specific 
exceptions to the rules). 
```
