### ISSUE TITLE
A New Secret base forcing 2 card draw

### ISSUE THREAD

**Issue by seitaer** [PlayersCommittee/gemp-swccg-public#59]
https://gemp.starwarsccg.org/gemp-swccg/game.html?gameId=344

LS turn 2. Attempted A New Secret Base. I only had 1 echo site which I pulled and hit done. I had a EBO but did not wish to draw. Game threw an error and forced me to draw (EBO), kept spawning the reserve deck window, until i drew it.

Since it says "up to" believe it should allow only 1 card draw.

**Additional**

I experienced a possibly related issue with ANSB. I was able to draw 2 "Echo" cards on the first turn I used it, but only one on subsequent turns. Namely, I did not let me draw one Echo site and one echo Effect.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
