### ISSUE TITLE
Beta version keeps crashing with a Unity error.

### ISSUE THREAD

**Issue by Talon-Jade** [PlayersCommittee/gemp-swccg-public#590]
- [x ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Me and the three other people I play with have been trying to use the beta and it will keep getting a Java/Unity error that makes the program unusable until we reload it.

## **To Reproduce**
1. Go to beta version
2. Play a game or watch a game in history
3. Error message pops up at the top
4. Gemp Beta becomes unusable.
5. See error

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Beta

## **Additional context**
![error](https://user-images.githubusercontent.com/109772680/180339081-0eddaa34-b06c-4e6a-9a7b-9d8adbe63a15.png)

**Comment by SWCCGArenaProject** [comment]
Thanks for this report, what's going on is the asset is named as .gif but is actually png data. Like this for example: https://res.starwarsccg.org/cards/Virtual18-Dark/large/adarktimefortherebelliontarkinsorders.gif

If you download that image and open it in a hex editor is has a png header. Epic duel doesn't understand this mis-naming yet so it's trying to decode that data as gif data but crashes like this.

1.8.5 should be going up in a few days with fix for this.

I appreciate the report, and sorry you had to deal with this for so long.
