### ISSUE TITLE
Vader with Lightsaber Unable to Swing in Battle With General Solo, Chewie, and Ewok Spearman

### ISSUE THREAD

**Issue by billbisco** [PlayersCommittee/gemp-swccg-public#591]
Please check this replay.  

Towards the end of the game, Vader with Saber is in a battle with Han, Chewie, and an Ewok Spearman.  He is never given an opportunity to strike.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=billbiscos$pow4htmmfzmpry2r

**Comment by EchoBaseTrooper** [comment]
If you watch the replay Vader does light up during the battle. You must have accidentally clicked pass.
