### ISSUE TITLE
Edcel preventing destinies at non-bg

### ISSUE THREAD

**Issue by rhendon82** [PlayersCommittee/gemp-swccg-public#598]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Leia + Leadership did not draw 2 destinies at senate with Edcel. He should only work at non-bgs.

## **To Reproduce**
Battle in senate against Edcel in majority and draw 2 destiny or try to.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=rhendon$jej9t608zt70bzt0

Turn 2 or 3 I believe.

## **Expected behavior**
Leia should have drawn 2 destiny.

**Comment by EchoBaseTrooper** [comment]
Coruscant Guard (V) says "neither player may draw more than one battle destiny here"
