### ISSUE TITLE
Star Destroyer: Launch Bay (or any generic starship site) counts as an Executor site for multiple cards

### ISSUE THREAD

**Issue by DSx61x4** [PlayersCommittee/gemp-swccg-public#601]
## **Describe the bug**
Flagship Operations is able to be deployed when there are four Executor Sites and a Star Destroyer: Launch Bay, which has been ruled to be illegal.  https://forum.starwarsccg.org/viewtopic.php?f=5&t=49048&p=763047&hilit=Launch+bay#p763047

## **To Reproduce**
1. Deploy Flagship Executor and Four Executor Sites and Star Destroyer:  Launch Bay
2. Attempt to deploy Flagship Operations

## **Game Replay ID:**
No replay available - I only witnessed it in a game.

## **Expected behavior**
Flagship Operations should ignore the Star Destroyer: Launch Bay for the purposes of deploying with a minimum of five sites on table

**Comment by jdipaolo1** [comment]
This issue is being reviewed by the Rules Team

**Comment by jdipaolo1** [comment]
More issues regarding this issue:
Cecius still deploys free to Tie Launch Bay (should not according to ruling cited to prevent FLOPs interaction)
Suba is really messed up - When Suba at Executor main corridor: can search library. Trooper deploys free to main corridor. Trooper deploys free to Tie Launch Bay. Trooper at main corridor gets +1 bonuses. Trooper at Tie Launch Bay gets no bonus.
When suba at Launch Bay: Trooper at launch bay gets +1 bonus. Troopers at Corridor do not get bonus. Suba can search reserve deck.
Suba is currently extremely confused and not consistent in any way.
3. Executor main corridor can move to and from Tie Launch Bay

**Comment by DSx61x4** [comment]
I'm not sure this belongs here - let me know if it needs its own separate bug report - but on DS turn 10 of this game:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fat_lenny$52syvkndvj75df2t
a battle at one Star Destroyer: Launch Bay caused the other Star Destroyer: Launch Bay deployed to Executor to become inexplicably and hilariously lost and all cards deployed there lost as well.

**Comment by DSx61x4** [comment]
> I'm not sure this belongs here - let me know if it needs its own separate bug report - but on DS turn 10 of this game:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fat_lenny$52syvkndvj75df2t
a battle at one Star Destroyer: Launch Bay caused the other Star Destroyer: Launch Bay deployed to Executor to become inexplicably and hilariously lost and all cards deployed there lost as well.

This has been submitted as a separate bug. [https://github.com/PlayersCommittee/gemp-swccg-public/issues/617](https://github.com/PlayersCommittee/gemp-swccg-public/issues/617)

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
