### ISSUE TITLE
LS Tatooine: Hutt Canyon allowing DS player to draw destiny when occupied by a Jawa

### ISSUE THREAD

**Issue by pete6982** [PlayersCommittee/gemp-swccg-public#603]
During a JP sealed league game, I had Kalit (Jawa) on a skiff with no driver at LS Tatooine: Hutt Canyon ("If you occupy with a Jawa, opponent may not draw battle destiny here"). This happened during battle on Jollyhut's turn 3. He allowed me to revert it and did not draw a destiny, but was able to before we reverted and declined to draw one after reverting. This happened on Microsoft Edge
Version 103.0.1264.62 (Official build) (64-bit). Here is the game file.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=pete6982$xuzjrhaj9p0xc48j

**Comment by MatthewHT** [comment]
I encountered a bug which seems like it might be related. I was still able to draw destiny even though my opponent had played Artoo, I Have A Bad Feeling About This.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MatthewHT$y6m9owa3f6h34l0c

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
