### ISSUE TITLE
Waiting for Server Response Time is 3+ seconds

### ISSUE THREAD

**Issue by forrest319** [PlayersCommittee/gemp-swccg-public#610]
Not sure if this a code issue, or a hardware issue.

Steps to reproduce:
1. Login to GEMP
2. F12 in your browser and navigate to the network tab
3. You can stay in the game hall or join a game - just watch the network waterfall and hover your mouse to see the timing break down
4. Waiting for server response is typically > 3 seconds.  The example screenshot shows the details from a call with a 4s time, and the example at the very top of the page was more than 9 seconds for the server to respond.  What's going on, are we waiting for a disk drive to spin up every time something happens? 

<img width="1849" alt="gemp server response time" src="https://user-images.githubusercontent.com/98128420/185490118-3ca86f6a-4f28-4cf6-8f90-98e987ab80dd.png">
.

**Comment by Gergall** [comment]
This is built into the spec for the underlying GEMP card game software (which is used by multiple different card games, most notably SWCCG and LOTR).

GEMP has a minimum delay between responding to requests. This helps prevent the server from getting overloaded.

The Players Committee is working towards long-term infrastructure improvements, so there is hope that the system will have better performance and stability in the future.
