### ISSUE TITLE
Star Destroyer Launch Bays 'Blowing Up'

### ISSUE THREAD

**Issue by papatkins** [PlayersCommittee/gemp-swccg-public#617]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Whenever a starship (LS or DS) is lost at a Star Destroyer Launch Bay and there are multiple RELATED Launch bays deployed, one or more launch bays are lost, along with everything at the site. 1, 2, or all related Launch bays can be lost when this occurs.

## **To Reproduce**
Deploy 2 or more Star Destroyer Launch Bays to the same star destroyer. After a battle, forfeit a ship that participated in the battle. 1, 2, or all launch bays will be lost. Tested losing a handful of characters and issue only occurred when starships or squadrons were lost. No methods of forfeiting/losing a ship were tested beyond forfeiting at end of a battle. If multiple ships/squadrons present, losing any 1 triggered the bug. DS and LS ships both trigger the bug.

## **Game Replay ID:**
Original game - DS turn 10. 2 launch bays deployed to executor, 1 squadron forfeited at end of battle. Other launch bay lost. This game is super long, skip ahead to other replays for much faster/more informative testing.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fat_lenny$52syvkndvj75df2t

Testing interactions when all launch bays deployed to same non-unique star destroyer. Found that number of launch bays lost is inconsistent and can be 1, 2, or all 3.  I did not discover how to consistently lose all or only some launch bays. At least 1 was lost every time a starship was lost at a launch bay after a battle. In all but one test the launch bay being lost was not where the battle took place.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fat_lenny$2q3tc0tsyf8fwyp7

Testing interactions when launch bays split between a non-unique star destroyer and Executor. When a single launch bay is present for each (2 on table, unrelated), no destruction occurs when a starship is lost. When the third is deployed, it is only lost when the battle took place at the related launch bay.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=fat_lenny$setn2rcccaemu3sn

## **Expected behavior**
Star Destroyer Launch Bays don't sympathetically explode when a starship next-door is lost.

## Client Platform
iOS

## **Additional context**
This bug is super cool.

**Comment by EchoBaseTrooper** [comment]
Fixed in most recent release.
