### ISSUE TITLE
Course Rough and Irritating not limiting battle destiny

### ISSUE THREAD

**Issue by mrdanielamor** [PlayersCommittee/gemp-swccg-public#621]
Dark side turn 3 battle.
List Side turn 3 Battle.
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Heisenberg$lazf25r1bbz88qo5

**Comment by JereelHunter** [comment]
I was also in this game. There appeared to be 2 more issues with destinies. 1) Tarkin wasn't adding destinies with an Imperial leader (even before coarse). Both of these issues happened in back-to-back battles, in similar circumstances

**Comment by MajinMarty** [comment]
Had the same yesterday. Destinies would not be limited using I hate sand even though the site did say dark couldn't draw more then one destiny. 

Also I Am your Father did not ping when a character was hit. 

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=MartyMcFly$07kgglq55lbq7azg
