### ISSUE TITLE
Persona Replacement Bug

### ISSUE THREAD

**Issue by hayesbug** [PlayersCommittee/gemp-swccg-public#623]
Turn 2 Luke TLJ should not be able to persona replace at an occupied site. Rules state "must obey all deployment restrictions listed on it's own card" for persona replacement.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Hayes$iciqkp162dfk5koj

**Comment by Gergall** [comment]
Can confirm that Luke TLJ should not have been allowed to persona replace in that situation.  His game text deployment restriction should have prevented him from persona replacing.

**Comment by EchoBaseTrooper** [comment]
Fixed in recent release
