### ISSUE TITLE
Eli Vanto bugged

### ISSUE THREAD

**Issue by bibfortuna25** [PlayersCommittee/gemp-swccg-public#625]
Dark side turn 4. When I used Eli’s text to upload a card, only Governor Pryce lit up. Eli didn’t “see” the interrupt. 

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bibfortuna$gxqcu3k0x1lp6v8f

**Comment by EchoBaseTrooper** [comment]
Fixed a few days ago
