### ISSUE TITLE
Dofine(V) plus Sand Effect

### ISSUE THREAD

**Issue by rjellison01** [PlayersCommittee/gemp-swccg-public#627]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=sac89837$vz88vckiq90puib8

Turn 7. P-59's shot was cancelled by Blaster Deflection. Sand effect was used and I drew a 5 for destiny. Total Battle Destiny was 5 instead of 6. 

Per Gregall, if a weapon's targeting is cancelled it is used but not considered 'fired' thus Dofine should go off.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
