### ISSUE TITLE
Kessel Run (V) deployed with empty Reserve Deck

### ISSUE THREAD

**Issue by jokerking16** [PlayersCommittee/gemp-swccg-public#628]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Despite not having a Reserve Deck, LS was able to deploy Kessel Run (V) on Kessel (V). During each move phase, the required response of "take a card off Kessel Run (v)" appeared, but LS was obviously unable to.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jokerking$eqb9ktoh3y31s37l

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
