### ISSUE TITLE
Sense was played against Control

### ISSUE THREAD

**Issue by mtennyson** [PlayersCommittee/gemp-swccg-public#629]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
Control was played to cancel a force drain, and the opponent was able to play Sense twice to cancel the Control, but Control is supposed to be immune to Sense.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tennymf$5ps6rf5yhfzufe1e

On ideatrack's Turn #12, he force drains at Hoth Defensive Perimeter, tennymf plays Control. ideatrack played 2 Sense cards back-to-back to cancel Control. He couldn't draw destiny because he didn't have cards in reserve deck. He was only playing Sense just to get them back into his reserve deck, because he was running low on force.

## **Expected behavior**
Player shouldn't be able to play Sense to cancel Control. Control is immune to Sense.

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by EchoBaseTrooper** [comment]
The function of Control that cancels a force drain is not immune to Sense.


AR 1-8
**Actions - Immune**
It is occasionally the case that some
portions of a card will be Immune to one of those
interrupts while other portions may not. All of the game
text of the card that precedes the phrase "Immune to X"
(where X is Sense, Alter, or Control) is protected from
cancellation from the appropriate Interrupt.
