### ISSUE TITLE
TTO not counting sites for "X"

### ISSUE THREAD

**Issue by DSx61x4** [PlayersCommittee/gemp-swccg-public#630]
## **Describe the bug**
When That Thing's Operational automatically triggers at the end of a control phase, it is not counting occupied sites for "X".  Note: it may just not be counting occupied generic sites in the total for "X".  I have not tested on non-generic sites.

## **To Reproduce**
1. Deploy TTO
2. Move DSII to a system with a (generic?) site
3. Occupy site and control system
4. During next control phase, do not click on TTO when highlighted and allow control phase to end and automatically trigger TTO.
5. TTO will ping 2 damage

## **Game Replay ID:**
[https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DSx61x4$s5rca5oasxvo09kc](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DSx61x4$s5rca5oasxvo09kc)

## **Expected behavior**
On DS turn 6, the ping damage should have been 3

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
