### ISSUE TITLE
Dash Rendar (V) not working when using Sand effect

### ISSUE THREAD

**Issue by tomtomtomtomtomtomtomtomtomtomtomtom** [PlayersCommittee/gemp-swccg-public#631]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

During a battle, I used Sand effect to reduce BD and was not prompted the option to use Dash Rendar (V) at end of battle. When we reverted and I did not use Sand effect, I was able to use Dash.

## **To Reproduce**
1. Deploy Sand effect and Dash Rendar (V) against a character satisfying his requirements
2. Battle and remove card from Sand effect

[## **Game Replay ID:**
](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tom$xgji5htgx151cgp1)

## **Expected behavior**
Expected to be able to be able to limit BD's with Sand effect and then also reduce power and attrition with Dash Rendar (V).

### **Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: Chrome
 - Version: 21H2

## **Additional context**
I was also using Kal Fal to reduce my opponent's total BD to 0 but Gergall told me I should still be able to use Dash with Kal Fal.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
