### ISSUE TITLE
Steady Steady Combo Cancels Immunity Incorrectly

### ISSUE THREAD

**Issue by CoffeePassport** [PlayersCommittee/gemp-swccg-public#632]
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CoffeePass$26zowq6uv28i4ct7

Turn 4 there is a battle in which immunity to attrition is canceled despite there not being two aliens of the same species in the battle.

**Comment by EchoBaseTrooper** [comment]
This is fixed now
