### ISSUE TITLE
Unable to capture pilot on Lost in Space with capital ship during move phase.

### ISSUE THREAD

**Issue by demodave99** [PlayersCommittee/gemp-swccg-public#634]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Light side was unable to capture Thrawn on Lost in Space during move phase, but was able to be rescued by DS.

## **To Reproduce**
1. Lost in space played after the pilot was forfeited.
2. Move/Deploy capital ship to the same system as Lost in Space.
3. Ability to capture the pilot was unavailable on Lost in Space (regardless of whether there was a character aboard the capital ship).

[## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Oni$50klkauovrglmqcc
Turn 5

## **Expected behavior**
During move phase, the pilot on Lost in space should have been able to be captured by LS capital ship.

### **Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [105.0.5195.127]

**Comment by EchoBaseTrooper** [comment]
This is not a bug. See the Capturing section of the AR on page C-4
>only the Dark Side may capture; if the
Light Side somehow controls a card which allows
capturing, the Light Side may not use the capturing
portion of that card. (Thus, Light cannot use a stolen
weapon that captures its target, nor can he capture
characters using Weather Vane or Lost In Space).
