### ISSUE TITLE
React Issue - Either "Jawa" or "CZ-3"

### ISSUE THREAD

**Issue by John-C-4** [PlayersCommittee/gemp-swccg-public#635]
The 'react' from CZ-3 doesn't allow me to deploy a Jawa.

I'm not sure if the problem is with CZ-3's react not working, or there is an issue with deploying a Jawa as a react as they require 1 Force from each player.

## **To Reproduce**
Have CZ-3 at a site with a LS force icon. Jawa in LS hand. Either have DS Force Drain or initiate battle. Make sure both sides have at least 1 Force available to pay for the Jawa's deploy cost. CZ-3 doesn't give the option to deploy the Jawa as a React

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=John_C$baeu05fk0n5mhelh

Dark Side Control Turn #4 is the first time.

## **Expected behavior**
I should have been given the option to deploy my Jawa(2) in response to the Force Drain (using 1 Force from each players pile)

## Client Platform
 - OS: Windows 10 Pro
 - Browser: Firefox
 - Version: 105.0.1

Happens again at DS Control #6 (this time with Het Nkik in LS hand as well, a unique Jawa)
Happens in at Battle Segment (with Het Nkik) as well at DS Battle #10

**Comment by EchoBaseTrooper** [comment]
The way this works on GEMP is you click CZ-3 to use its react text. CZ-3 did light up at the correct time:
![image](https://user-images.githubusercontent.com/45436940/201414451-f26adf59-fcbd-428c-8477-17d2dbe39a95.png)
