### ISSUE TITLE
General Solo (V) sometimes(rarely?) wrong about if an Interrupt can be played

### ISSUE THREAD

**Issue by Gergall** [PlayersCommittee/gemp-swccg-public#637]
**_Because the situation is potentially rare I think this seems like a low priority but I wanted to log it anyway._**

- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
In some (possibly rare) circumstances General Solo (V) may allow you to select an Interrupt to play, but then it cannot be completed so it sort of "fizzles" and remains in Reserve Deck.  Unplayable Interrupts should not be selectable in the first place... and usually aren't.

## **To Reproduce**
1. LS should have General Solo (V) out, 2 Force saved and a Clash Of Sabers in Reserve Deck.
2. DS should have First Strike and initiate battle against General Solo (V).
3. LS uses General Solo (V) and selects Clash Of Sabers (presumably the function to search Reserve Deck for a copy of Uncontrollable Fury)
4. LS uses 1 Force for General Solo (V)
5. LS uses 1 Force for First Strike
6. LS has no Force remaining to pay for Clash Of Sabers itself, so it sort of "fizzles" and remains in Reserve Deck and the Force spent remains used.

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=GergallTS2$wvra1rxgtjap9o6r
The battle initiated by Dark on Dark Turn #3.

## **Expected behavior**
Normally General Solo (V) prevents the selection of Interrupts that cannot be played or paid for.  In this scenario, he should have prevented the selection of Clash Of Sabers.

## **Screenshots**
![image](https://user-images.githubusercontent.com/6243118/194799905-6834c348-dd58-4b0a-b6eb-1938e038bd47.png)

## **Additional context**
I did a fair bit of testing and found that General Solo (V) usually DOES properly account for First Strike and grabber costs, which is very impressive!  For example, I cannot replicate this bug with Blue Milk against First Strike.  I cannot replicate this bug with Don't Get Cocky when I am unable to pay to stack it on a grabber.
I think General Solo (V) getting confused on Clash Of Sabers might have something to do with Clash having several functions, each with a different cost.  I can certainly appreciate how that would make the logic very complicated.

**Comment by Gergall** [comment]
To reiterate from the top of the post, since it would be easy to miss it:

Because the situation is potentially rare I think this seems like a low priority but I wanted to log it anyway.

**Comment by EchoBaseTrooper** [comment]
The error here is that specific function of Clash Of Sabers checks GameConditions.canUseForce instead of GameConditions.canUseForceToPlayInterrupt. Because of this it does not check if you can also pay additional costs (like First Strike) when determining if the interrupt is playable.
