### ISSUE TITLE
Homing Beacon Not Working

### ISSUE THREAD

**Issue by arebelspy** [PlayersCommittee/gemp-swccg-public#64]
Homing Beacon lights up to let you react, but when you click the ship to react, nothing happens. Stays lit up. You can keep clicking, but doesn't do anything.

Screenshots and replays here:
https://forum.starwarsccg.org/viewtopic.php?f=1105&t=73014

**Comment by DSx61x4** [comment]
It also does not allow a player to cancel landing claw.

**Comment by EchoBaseTrooper** [comment]
Should be fixed now
