### ISSUE TITLE
Weather Vane not rotating correctly

### ISSUE THREAD

**Issue by jagteq** [PlayersCommittee/gemp-swccg-public#640]
## **Describe the bug**
Weather Vane will sometimes rotate incorrectly.  On some occasions, it will roate from due West to due East, skipping over being upright and thus denying Light the retrieval for rotating it fully.  Other times, it will fail to rotate entirely, or will rotate in the wrong direction when Light Side drains.

## **To Reproduce**
I do not know why this is happening and thus cannot instruct on how to replicate it.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jagteq$tstd6p7g8dsvvmxq
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jagteq$g21k4ulnosudf95j

## **Expected behavior**
Weather Vane should rotate 90 degrees clockwise when LS drains or battles, and 90 degrees counterclockwise when DS battles, except from due North/0 degrees.

**Comment by EchoBaseTrooper** [comment]
It looks like reverts mess with this. After a revert Weather Vane (V) thinks it is not rotated at all even though it shows the correct orientation on your screen before the next battle/drain that would rotate it.
