### ISSUE TITLE
Haven not adding battle destiny. 

### ISSUE THREAD

**Issue by JohnMcD34** [PlayersCommittee/gemp-swccg-public#643]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Haven adding a battle destiny is an optional ability. You have to click on it during the battle to add the battle destiny.

If you did click to add a battle destiny and it wasn't added please add a replay and reopen this.

**Comment by JohnMcD34** [comment]
I will try it again, but I don’t believe I got a chance to click it. It went straight from weapon phase to you have to lose X force. 

Thanks,
John
