### ISSUE TITLE
Death Star II is deploying to deep space parsec 8 (rather than orbiting endor)

### ISSUE THREAD

**Issue by charlesmhickeyjr** [PlayersCommittee/gemp-swccg-public#644]
I have played two games in a row with Endor Operations / TTO.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Teacher$prak0pwj8icumgve
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Teacher$kam48el9ow55eqco

Both games the deployment of Death Star II locates it in deep space rather than orbiting Endor

**Comment by EchoBaseTrooper** [comment]
This is fixed now
