### ISSUE TITLE
Hobbie, Red Squadron 4 X="3"

### ISSUE THREAD

**Issue by daz-1** [PlayersCommittee/gemp-swccg-public#647]
## **Describe the bug**
When firing a laser cannon on red squadron 4, card states use 2 force for X=3.  Used 2 force and it only added 2 force to the destiny draw rather than 3 like the starship card describes

## **To Reproduce**
1. deploy piloted red squadron 4 with laser cannon
2. attack and fire laser cannon at a starship
3. pay 2 force which should then add +2 to the destiny draw
4.
5. see that the draw is really only destiny +2 rather than +3

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=daz_1$umi6dc1mjvfxx4p5
turn #3 battle phase.  battle at tatooine system

## **Expected behavior**
should have been +3 and starship should have been lost immediately

## **Screenshots**
![image](https://user-images.githubusercontent.com/119803298/205501547-ffeacf86-3ff3-4077-9f32-3639e81c7bd1.png)

### **Desktop (please complete the following information):**
 - OS: windows
 - browser: edge

**Comment by EchoBaseTrooper** [comment]
The way this works is you pay 0 force to fire the weapon and then click on the starship to use its text to use 2 force and make X = 3.
