### ISSUE TITLE
"game cancelled due to an error"

### ISSUE THREAD

**Issue by Darthjeeps** [PlayersCommittee/gemp-swccg-public#651]
[Dec 18 10:33:19] darthjeeps://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=darthjeeps$inltngbu8s4dk2jo
[Dec 18 10:35:06] darthjeeps: It (game cancelled) happened as soon as the new Bib Fortuna was deployed to Jabba's Sail Barge at the Pit.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
