### ISSUE TITLE
Imperial Enforcement Worked Outside of Battle

### ISSUE THREAD

**Issue by CoffeePassport** [PlayersCommittee/gemp-swccg-public#652]
On turn 6 in this game, Enforcement was used to take re-draw a Sniper weapon destiny draw in the control phase -- card was recently changed to only work in battle and the text is correct on the image but still working outside of battle:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=CoffeePass$ppe03g6mp5t4n2wc

**Comment by EchoBaseTrooper** [comment]
This had been fixed a few days before this bug was reported. If this happens again feel free to reopen this bug report.
