### ISSUE TITLE
You Are Beaten lasting additional turn

### ISSUE THREAD

**Issue by tomtomtomtomtomtomtomtomtomtomtomtom** [PlayersCommittee/gemp-swccg-public#653]
## **Describe the bug**
DS player uses YAB on LS turn. Character excluded until end of 2nd DS turn after playing YAB instead of end of next DS turn. 

## **To Reproduce**
1. YAB a character.

## **Game Replay ID:**
[](https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tom$uxcx90fcny57bsy5)

## **Expected behavior**
 YAB wears off after the next DS turn since it was played during LS turn.

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 pro 22H2 build 19045.2364
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 108.0.5359.125 

## **Additional context**
A Sense was played and cancelled with Alter on the YAB.

**Comment by EchoBaseTrooper** [comment]
Do you have a replay?

**Comment by tomtomtomtomtomtomtomtomtomtomtomtom** [comment]
Ah! Here it is:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tom$uxcx90fcny57bsy5

Turn 4 or 5.
________________________________

**Comment by EchoBaseTrooper** [comment]
From watching the replay YAB was played at the beginning of dark's turn after activating, not during the light side player's turn.

**Comment by tomtomtomtomtomtomtomtomtomtomtomtom** [comment]
Gotcha. Must have confused it with Barrier. Thank you for checking!

________________________________
