### ISSUE TITLE
Power of the Hutt doesn’t pull Bib(v)

### ISSUE THREAD

**Issue by BadEwok** [PlayersCommittee/gemp-swccg-public#659]
- [ ] Did you search through the list of open issues: yes

## **Describe the bug**
Power of the Hutt should pull any persona of Bib but doesn’t seem to allow me to pull pull Bib Fortuna, heir to the palace. 

## **Expected behavior**
That Power of the Hutt would let me pull new Bib.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
