### ISSUE TITLE
No longer getting rare foils for league wins

### ISSUE THREAD

**Issue by bkippel** [PlayersCommittee/gemp-swccg-public#66]
I am no longer getting rare foils for league game wins.  My 9,11,13, and 15th league wins awarded common/uncommon foils instead of rares.

**Comment by jokerking16** [comment]
If this was in the Jawa league, it resets when the 2nd series starts.  I show you (at the time of this post) with 8 wins in series 1, and 10 wins in series 2.

**Comment by bkippel** [comment]
Thanks, I had missed Series 1 ending and Series 2 starting.

**Comment by jdipaolo1** [comment]
So is this still an issue, or can we close it?

**Comment by bkippel** [comment]
Ok to close
