### ISSUE TITLE
Could not swing twice with Mace, Redraw with Jedi Lev, opp could not use Maul or cancel destiny with Jodo Kast

### ISSUE THREAD

**Issue by jagteq** [PlayersCommittee/gemp-swccg-public#661]
As reported in the title, throughout the game.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=jagteq$4u89rm2byns890dp

**Comment by EchoBaseTrooper** [comment]
I didn't watch the whole replay but I'm guessing Maul's errata text is responsible for everything except the Mace thing. If there is really a bug here feel free to reopen.
