### ISSUE TITLE
Observation Holocam (v) not letting characters move during LS deploy phase

### ISSUE THREAD

**Issue by rsersen** [PlayersCommittee/gemp-swccg-public#663]
Holocam (v) says _"If opponent just deployed a character or vehicle here, may lose 1 Force to move your character to here using landspeed (at normal use of the Force)."_

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BrenDerlin$rhpuk5gq4o7qahyn

Light side turn 2 deploy phase. Light deploys Padme to Chasm Walkway with Holocam (v) there, while Maul is at the adjacent Downtown Plaza with 1 Force saved. 

Holocam (v) does not light up to allow dark to respond and move Maul over. Don't see any other cards on table that would have made Maul cost more than 1 Force to move. We did revert to try the deployment again and make sure we didn't miss the window, but same result.

Holocam (v) does light up afterwards as a top-level action to use the additional text (place out of play to draw top card of Reserve).

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
