### ISSUE TITLE
Much Anger in Him

### ISSUE THREAD

**Issue by SWCCG2Moon** [PlayersCommittee/gemp-swccg-public#665]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?  Yes

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=SWCCG2Moon$2bgucwafedbntqev

## **Expected behavior**
 I expected the force loss to not trigger

**Comment by EchoBaseTrooper** [comment]
Page 4-3 of the AR explains the difference between presence and present. Being in an enclosed vehicle means the character is not **present** at the location but they still have **presence** at the location.
