### ISSUE TITLE
Game canceled during an OCS game

### ISSUE THREAD

**Issue by cringwell** [PlayersCommittee/gemp-swccg-public#666]
Turn 11 for the LS players turn.  I battled at the 2-2 Lothal Site (DS players).  He went to react using the 2-0 site and it just canceled the game.  I assume he had an OTSD trooper the deploys free in hand (that absorbs attrition).  But it cancelled before he could deploy the card.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=advocate$rj3b4um0apryvxvz

- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issu
## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
