### ISSUE TITLE
Force drain bonus allowed after Jedi Test #1 had been completed

### ISSUE THREAD

**Issue by mtennyson** [PlayersCommittee/gemp-swccg-public#673]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue? yes

## **Describe the bug**
Expand the Empire was played on a site (Spaceport City) that gave a +1 force drain bonus to dark side. Jedi Test 1 was completed by the light side. On the next turn, dark side still received a +1 bonus at the site adjacent to Expand the Empire. I think the drain bonus should have been canceled.

## **To Reproduce**
1. In the replay given below, go to MPac's turn 7. You will see he is allowed to drain for 2 at Spaceport Docking Bay. In real-time during the game, when zooming on the Spaceport Docking Bay, it showed a +1 drain bonus was applied. 

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tennymf$vmtcbeh7fl1f59dk

## **Expected behavior**
Force drain bonus should have been canceled.

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 110.0.1587.50 (Official build) (64-bit)

**Comment by EchoBaseTrooper** [comment]
This is weird, but it is not a bug. "opponent's force drain bonuses" means "force drain bonuses coming from the opponent's cards". When Expand The Empire copies the force drain +1 text to your location, that bonus is now considered to be coming from your card so Great Warrior doesn't cancel it.
