### ISSUE TITLE
Profit Ping Damage Bug

### ISSUE THREAD

**Issue by DTartagOne** [PlayersCommittee/gemp-swccg-public#674]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes
## **Describe the bug**
When playing against You Can Either Profit By This, the dark side player was forced to lose cards off of the top of their Reserve Deck when talking the Profit damage
## **To Reproduce**
3. During the LS player's Control phase, while Profit is on the 7 side, the DS player must lose force equal to the number of battlegrounds occupied by X characters
4.
5. See error

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=DTartagOne$600z0gkiulvdffjp
## **Expected behavior**

The DS player should have been able to lose cards from anywhere.

**Comment by EchoBaseTrooper** [comment]
Fixed in latest release
