### ISSUE TITLE
Lando With Vibro-Ax, deploy reduction

### ISSUE THREAD

**Issue by thang2ine** [PlayersCommittee/gemp-swccg-public#679]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue? Yes

## **Describe the bug**

Lando With Vibro-Ax is not deploying for 4 to all Tatooine sites.

## **To Reproduce**
Steps to reproduce the behavior: I deployed him to Tatooine: City Outskirts and it costed 6 force, it should be 4 force

## **Expected behavior**
 Should have been deployed for 4 force.

## **Screenshots**
![image](https://user-images.githubusercontent.com/127642847/224523332-a865dec9-8537-4092-a286-83b06e476d3a.png)

## Client Platform
Laptop
 - OS: [Windows]
 - Browser [Firefox]
 - Version []

**Comment by EchoBaseTrooper** [comment]
The 7 side of your objective says "Aliens may not have their deploy cost modified to Tatooine locations." That includes the -2 from Lando's text.
