### ISSUE TITLE
Let wookie win (v) not showing all possible effects

### ISSUE THREAD

**Issue by joe-death** [PlayersCommittee/gemp-swccg-public#685]
https://gemp.starwarsccg.org/gemp-swccg/game.html?gameId=d217ab97ab9e-763a-2e21-b515-1b5fde10

Played Let the wookie win (v) as starter. Did not show multiple effects in my deck as selectable starting with Immune to Alter attribute including but not limited to Echo Base Operations.

**Comment by EchoBaseTrooper** [comment]
That is the link to your live game, not the replay.

But even without the replay I can tell this is not a bug. At the beginning of the game you did not occupy 3 Echo sites so you did not meet the deployment requirement for Echo Base Operations.

**Comment by EchoBaseTrooper** [comment]
> Ya I went back and reran it, I see the issue, sorry for the bother.

No problem. It's better to report too many things and have some of them end up not being bugs. Otherwise we could end up with bugs not being reported at all. Thanks for the report even though it didn't end up being a bug!
