### ISSUE TITLE
Protector and HC&F(V)

### ISSUE THREAD

**Issue by fastlearner-ai** [PlayersCommittee/gemp-swccg-public#69]
I cannot get the "lose Chewie from hand" portion of Protector to work in GEMP if the "Chewie" I have in hand is Han, Chewie, and The Falcon (V). I've tested twice and both times there is just never an option to play the interrupt even though the conditions (chewie in hand, leia in battle) are met.

Protector seems to work if I have other kinds of Chewie in hand, and it also works for adding 2 destiny when Leia is with HC&F(V). So that portion of the Protector text correctly recognizes HC&F(V) as a "Chewie".

I can take HC&F(V) into hand as a persona of Han with Where's Han? so apparently it IS a persona of Han while not on table. It just doesn't seem to be a persona of Chewie while in hand for some reason.

Edit: I did a bit more testing. Both HC&F (V) and non-(V) are personas of Han and Chewie for purposes of searching (Where's Han?, Wookie Roar) but neither of them works with Protector's "lose Chewie from hand" function.

**Comment by kpbabb** [comment]
Looking into this one

**Comment by fastlearner-ai** [comment]
My best guess is that in the Filters class it doesn't work right for checking for a persona from hand when that persona happens to be an AbstractPermanentAboard permanent pilot persona

**Comment by kpbabb** [comment]
Sounds reasonable.  Just tested it with HCF, HCFv and Chewie Protector, only get prompted to play Protector with Chewie Protector in hand, and can't use either HCF to Satisfy.  I'll work on a fix

**Comment by fastlearner-ai** [comment]
Cool. Btw I was trying to get the virtual machine to work earlier so I can do some testing/debugging myself. But I had some issues getting it to start up. Who do you suggest I email about that?

**Comment by kpbabb** [comment]
Are you on Slack?  If so, what's your user name?

**Comment by fastlearner-ai** [comment]
If you link me I'll join

**Comment by kpbabb** [comment]
Ok, I created a pull request for a fix, but I don't think I have the rights to link it here
