### ISSUE TITLE
Big One and They Must Never Again Leave This City

### ISSUE THREAD

**Issue by BadEwok** [PlayersCommittee/gemp-swccg-public#690]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
- yes

## **Describe the bug**

I lost a Tie at the Big One which was located at Bespin. They must never again… was on the table. I was unable to take the Tie into my hand. I believe the Big One at Bespin ought to count as a Bespin location. 

## **To Reproduce**
1. Deploy Bespin, Big One and They must never…
2. Deploy Tie to Big One
3. Draw asteroid destiny to make the Tie lost
4. …see what happens. 
(in the game the Tie was lost in a battle but the result should be the same). 

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BadEwok$gf0m33r8yovk5w0m

## **Expected behavior**

I expected that asteroid sectors at Bespin would count as Bespin locations. 

### **Smartphone (please complete the following information):**
 -  iPhone10

**Comment by EchoBaseTrooper** [comment]
This is explained on page 9-11 of the AR:
>**Asteroid Sectors**
Asteroid sectors are related to a system location, but
not to the planet's sites. They are not part of the planet
and thus do not take on its name (e.g., asteroid sectors
at Dagobah are not "Dagobah locations"
