### ISSUE TITLE
The Empire Knows We're Here allowed to deploy systems

### ISSUE THREAD

**Issue by rsersen** [PlayersCommittee/gemp-swccg-public#709]
Played a game on 10/5 against The Empire Knows We're Here. LS player started ANSB non-v and used it pull Kiffex into hand, and was later able to deploy it.

LS was on the 7  side of their objective when the deployment occurred, but the 0 side states "For remainder of game ... You may not deploy systems."

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=rsersen$v1spj62a9s2ujivz

Occurred on LS turn 3

![image](https://github.com/PlayersCommittee/gemp-swccg-public/assets/86428918/0289480f-2787-40b5-a988-5dc75dfa279b)

**Comment by AaronKingery** [comment]
Similarly, in game: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ArchmageBB$1g5tsycyohhnj6fn
Dark was allowed to use Lando (V) (Dark Side) text to return Echo Base Garrison to my used pile. That ability should only work non-immune to alter, but per the obj EBG should be immune to alter for remainder of the game.
