### ISSUE TITLE
Rey not triggering when redeployed with Are You Okay?

### ISSUE THREAD

**Issue by bibfortuna25** [PlayersCommittee/gemp-swccg-public#713]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
During a battle I forfeited Rey, and used Are You Okay? to redeploy her to the battle site. Upon being redeployed, I could not use her text to take a card into hand from my Used Pile. 

## **To Reproduce**
1. Initiate battle on a turn where you did not deploy Rey, forfeit her, then use AYO to redeploy her. 

## **Game Replay ID:
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bibfortuna$72y3hsjntnpsol4f

Light side turn 8. 

## **Expected behavior**
Rey should let you take a card into hand with her text. 

## **Additional context**
According to Gergall on the Rules Forum, this is a legal play. https://forum.starwarsccg.org/viewtopic.php?p=1415516#p1415516

**Comment by Gergall** [comment]
So sorry bibfortuna.  I made a mistake, and GEMP is correct.  Rey cannot search because she goes inactive.

Even if she were the last character forfeited, the battle is still ongoing at that moment so she can't search.

No bug here.
