### ISSUE TITLE
Understand Art, Understand A Species is bugged

### ISSUE THREAD

**Issue by bibfortuna25** [PlayersCommittee/gemp-swccg-public#733]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**

During battle, Understand Art, Understand A Species was played to target Luke With Lightsaber. UAUAS did not reduce Luke’s power and forfeit like it should have. Even though Luke does not have any characteristics, the wording of the card should reduce his power and forfeit. 

## **To Reproduce**
Play Understand Art Understand A Species on a character who does not have any characteristics.  

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bibfortuna$zg8pcfqd8mh93i6l

## **Expected behavior**
UAUAS should reduce the target’s power and forfeit.

**Comment by bibfortuna25** [comment]
Forgot to note, the bug occurred during light side turn 8.

**Comment by Gergall** [comment]
Can confirm bibfortuna25 is correct, it should always affect the power and forfeit of the target character even if they have no characteristics.
