### ISSUE TITLE
Chiss not recognized as a species

### ISSUE THREAD

**Issue by ejchien** [PlayersCommittee/gemp-swccg-public#734]
In this game, My Kind of Scum did not recognize Mit'thrawn as a valid "unique alien with a species" to be my rep and put my objective out of play: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=echien$yh4ync11t4a1e7u2

Gergall confirmed that this is a bug, because Mit'thrawn should be a valid rep: https://forum.starwarsccg.org/viewtopic.php?p=1420484#p1420484

**Comment by Gergall** [comment]
Yeah, I checked with the rules team and we all agree that Mitth'raw'nuruodo is a valid Rep, with Chiss as his species.  Thanks for putting in the bug report!
