### ISSUE TITLE
Blaster Deflection Lost - Not Able to Retarget

### ISSUE THREAD

**Issue by stimpy08** [PlayersCommittee/gemp-swccg-public#738]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
- [ ] Yes

## **Describe the bug**
DS Turn 6 - Opponent Shadow Collective vs my Clones. He battles me with EPP 4lom, EPP Dengar, and Xizor with a blaster. I have Yoda MOTF with a jedi lightsaber v. Dengar targets Yoda, I have blaster deflection and 6 or 7 force saved - I am presented with the option to play deflection used or lost. I choose lost, and then am prompted to select the character to retarget. However, none of the DS characters light up as options - only Yoda was able to be targeted. 

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=stimpy$c2hxnuraialxwjqm

## **Expected behavior**

I expected to be able to play blaster deflection lost to retarget to an opponent's character to be hit. 

## **Screenshots**

![image](https://github.com/PlayersCommittee/gemp-swccg-public/assets/112194476/ae2efe75-51cc-460b-bbfe-f64cf9b4df5b)
![image](https://github.com/PlayersCommittee/gemp-swccg-public/assets/112194476/9e3028be-c670-41f2-90f7-9a28acd6e5bf)

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge

**Comment by EchoBaseTrooper** [comment]
The message says "Choose character to re-target from, or click 'Done' to cancel". You needed to click on Yoda first and then it would have had you select the opponent's character as the next step.
