### ISSUE TITLE
Big One (LS) applies FD bonus when Great Warrior is passed..

### ISSUE THREAD

**Issue by tim3worm** [PlayersCommittee/gemp-swccg-public#742]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Jedi Test #1 Great warrior cancels FD bonuses, however opponent still gets a FD bonus at Big One when they control.

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Do you have a replay?

**Comment by EchoBaseTrooper** [comment]
This is not a bug. Drain +1 text in the dark side text box of a light side location does not count as an opponent's force bonus because it is not coming from their card.
![image](https://github.com/PlayersCommittee/gemp-swccg-public/assets/45436940/f5f9f81a-4c78-4bf5-bb16-5433c1db171c)

**Comment by tim3worm** [comment]
thank you, I understand it only cancels FD bonuses that come from DS cards
from your explanation.

**Comment by EchoBaseTrooper** [comment]
Yeah it's a confusing rule. Thanks for reporting this even though it didn't end up being a bug.
