### ISSUE TITLE
Vader Free Relocate appears to not work

### ISSUE THREAD

**Issue by blakesilkwood** [PlayersCommittee/gemp-swccg-public#744]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?
Yes

## **Describe the bug**
Interaction between Vader's Machination and the Text on Lothal Jedi Temple. I used the  relocate text on Vader's Machination, and it cost me +2 Force due to Temple Text. It should be free per text on my effect.

## **To Reproduce**
Game ID Attached

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bsilkwoo$icwqrjyongdv0acx
I was not able to relocate on LS Turn #1, since I didnt have force saved
On LS Turn #2, I relocated for 2 force.

## **Expected behavior**
I should be able to make the relocate for free. Instead, it cost me 2 force.

## **Screenshots**
<img width="959" alt="image" src="https://github.com/PlayersCommittee/gemp-swccg-public/assets/94271296/7aa72b52-5c95-444c-af69-0f009caab85c">

## **Additional context**
![Screenshot 2024-02-25 110459](https://github.com/PlayersCommittee/gemp-swccg-public/assets/94271296/17c3781f-8c2a-47d4-82f5-c9b162fbb7c8)

**Comment by jetsaredim** [comment]
@blakesilkwood thanks for the bug report.  What I believe is the fix for this should go out with the next gemp deployment later this week.  Will let you know so you can re-test/verify.

**Comment by jetsaredim** [comment]
this is live now
