### ISSUE TITLE
K'lor'slug Not activating during battle to add power

### ISSUE THREAD

**Issue by benbanyas** [PlayersCommittee/gemp-swccg-public#745]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already a report for this issue?
- [ ]  I used the search function and did not find this issue.

## **Describe the bug**
When initiating a battle and going through all of the battle steps, K'lor'slug never allowed LS to use ability to ad power with use of Force. 

## **To Reproduce**
1. Initiate battle with K'lor'slug, ability, and cards in force pile
2. Go through battle steps
3. See error (no option to use K'lor'slug)

### **Desktop (please complete the following information):**
 - OS: iOS (iPad)
 - Browser: Chrome

### **Smartphone (please complete the following information):**
 - Version 122.0.6261.62

**Comment by EchoBaseTrooper** [comment]
This is not a bug. K'lor'slug says "For each unit of ability you have present during a battle," and you did not have any ability present in the battle.

The pilots are not present at the system and permanent pilots don't count either as noted in the AR:
>Permanent pilots, passengers, and astromechs are present aboard their respective starship or vehicle

(I asked the rules advocate about this today)

**Comment by benbanyas** [comment]
Thank you for checking and explaining!

Ben Banyas
Leadership, Fundraising, & Event Consultant
(412) 417-6339
www.benspiration.com
