### ISSUE TITLE
TMNALTC causing Dark Side Cards to be move +1

### ISSUE THREAD

**Issue by babombdude** [PlayersCommittee/gemp-swccg-public#747]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Dark player was attempting to shuttle GMTv to Executor from CC downtown plaza and it cost two force. 

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=babomb$znqtj8c5uon232s0
## **Expected behavior**

There should have been no increased cost for the shuttle. Just prior to the revert depicted in the screenshot, GMTv cost 2 force to shuttle.
![Screenshot 2024-02-28 221629](https://github.com/PlayersCommittee/gemp-swccg-public/assets/161670888/fe83345e-e54e-484d-8f19-2d812fd8b23b)

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by EchoBaseTrooper** [comment]
This is not a bug. The extra force was not from TMNALTC. From the Shuttling section of the AR:
>The cost of shuttling is cumulatively increased by 1 for each cloud sector between the planet system and its related sites.
