### ISSUE TITLE
Furry Fury did not interact with HCFv in battle

### ISSUE THREAD

**Issue by taylorisg** [PlayersCommittee/gemp-swccg-public#748]
- [X ] Did you search through the list of **open issues** _first_ to ensure that there is not already a report for this issue?

## **Describe the bug**

During a battle with LS playing Han, Chewie, and the Falcon V, DS player had Furry Fury in hand but was never afforded the prompt to play the Lost gametext to draw destinies & reduce power/attrition despite having available life force in reserve to draw destinies.

## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**
 https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=tgosiaco$zd3se3ena2j8kahh
Turn #10 Light Side

### **Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

## **Additional context**
If there is a rules nuance I’m not aware of, apologies for the inconvenience!

**Comment by EchoBaseTrooper** [comment]
There must be attrition to subtract from to play Furry Fury. In this case your opponent did not draw battle destiny so attrition against you didn't exist.

**Comment by taylorisg** [comment]
Adam,

Thanks very much for the clarification, neither my opponent or I could
figure it out!
