### ISSUE TITLE
Vaders Anger not allowing Vader to follow a character that just moved away

### ISSUE THREAD

**Issue by deadbody55418** [PlayersCommittee/gemp-swccg-public#759]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Playing ROTS Vader, Vader at a cloud city site with multiple LS dude, he moved them away, I had force active (Vaders Anger is free) at no time was I able to play vaders anger to follow.
## **To Reproduce**
3. 
4.
5. See error

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=deadbody$khoivzhp4scdus10
## **Expected behavior**

Vader should have been able to follow
### **Desktop (please complete the following information):**
Firefox

**Comment by EchoBaseTrooper** [comment]
Vader had already made a regular move that turn with Vader's Machination. He isn't able to perform a second regular move in a turn with Vader's Anger (V).
