### ISSUE TITLE
<>Farm is currently subject to the One Rule in GEMP, but per the rules team should not be.

### ISSUE THREAD

**Issue by BlackbeardBen** [PlayersCommittee/gemp-swccg-public#772]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

Yes

## **Describe the bug**

The puller text on light side card <>Farm should not be subject to the One Rule, as per the rules team:
https://discord.com/channels/401469156907679746/749414231043997756/1257772329602125994

That means <>Farm should be able to deploy or attempt to deploy a Hydroponics Station or Vaporator an unlimited number of times during your deploy phase, similar to how Death Star: Docking Control Room 327 works (though the wording is different).

However, as currently programmed in GEMP, <>Farm only lets the player pull one Hydroponics Station or Vaporator per deploy phase.

The One Rule (p. 24 of the 2023 AR) specifies that it only applies when both a time frame is specified, and language that indicates that the language is singular is used (like the words 'a', 'an', 'one', or 'once').  Note that<>Farm does not use any word to indicate that the action is singular: "During your deploy phase, Hydroponics Station or Vaporator may deploy here from reserve deck, reshuffle."

## **To Reproduce**
1. Start game; get <>Farm on table
2. During your deploy phase, click on <>Farm to pull a Hydroponics Station or Vaporator, and deploy one.
3. After deploying one (or attempting to), see error that you are not able to search your reserve deck again.

## **Game Replay ID:**

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=BenKenobi$21mm7ax0uwv629el

## **Expected behavior**

After pulling (or attempting to pull) one Hydroponics Station or Vaporator during your deploy phase, you should be able to attempt again.

## **Screenshots**

N/A

### **Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 126.0.6478.127 (Official Build) (64-bit)

### **Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A

## **Additional context**
N/A

**Comment by Gergall** [comment]
Yes the Rules Team has confirmed this is a bug.

If it helps, similar gameplay function can be found on "Death Star: Docking Control Room 327" which allows the deployment of multiple docking bays instead of just one per turn.

**Comment by Gergall** [comment]
This bug fix is live.  Enjoy your farming.
