### ISSUE TITLE
Game Crash: OCS Game ROTS Maul vs Saga Luke

### ISSUE THREAD

**Issue by KrazyKarlOSU** [PlayersCommittee/gemp-swccg-public#787]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Game cancelled due a bug after Luke was hit by Aurra (Game play was sent via PM to Gergell per Tom's request)
## **To Reproduce**
3. 
4.
5. See error

## **Additional context**

![image](https://github.com/user-attachments/assets/9c17e545-0f23-448c-b236-348aad98b9e5)

**Comment by Gergall** [comment]
I have received replays from both players perspectives.
