### ISSUE TITLE
Young Fool doesn't function to cancel jedi presence

### ISSUE THREAD

**Issue by LOMHawkeye** [PlayersCommittee/gemp-swccg-public#805]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Young Fool (v) doesn't function for canceling Jedi Presence.

## **To Reproduce**
1. In battle LS plays Jedi Presence
2. DS has Young Fool (V) in hand, and it won't illuminate to allow canceling Jedi Presence

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=LOMHawkeye$f1frnrb6y78net3g

## **Expected behavior**
When LS plays Jedi Presence and DS has Young Fool (v) in hand it should allow them to cancel Jedi Presence.

**Comment by EchoBaseTrooper** [comment]
Young Fool (V) had been grabbed. It didn't light up because you didn't have enough force to play it.
